### ISSUE TITLE
Make docs easier to find from GitHub

### ISSUE THREAD

**Issue by ardalis** [spectreconsole/spectre.console#1023]
Add a prominent link to spectreconsole.net from the README file. There's a link on the right but if you don't see it you should be able to find a link near the top of the README.

**Comment by gakera** [comment]
I found the https://github.com/spectreconsole/spectre.console#documentation Documentation section quite easily from the readme, is it new since this issue was created?

**Comment by ardalis** [comment]
Hmm, no, but I totally didn't see it when I was looking for it. Probably because it's below the fold past a bunch of images. Still, it *is* in the TOC so probably shame on me. Up to the author if they think it's worth putting something higher up. Thanks for pointing it out!

**Comment by patriksvensson** [comment]
@ardalis I think you have a valid point. If you would submit a PR for the documentation link at the top I would appreciate it!

**Comment by nils-a** [comment]
Closing this as resolved, since commit https://github.com/spectreconsole/spectre.console/commit/02f9d264730c1076a701be3b513ce3188d04fcb5
