### ISSUE TITLE
Markup parsing exception

### ISSUE THREAD

**Issue by WolfBublitz** [spectreconsole/spectre.console#1024]
**Information**
 - OS: Windows
 - Version: 0.45
 - Terminal: any

**Describe the bug**
With version 0.44 the following worked:
```c#
new Markup("[white][[[/][white]]][/]")
```

With version 0.45 the code from above crashes with:
>Unhandled exception. System.InvalidOperationException: Could not find color or style 'white]'.
   at Spectre.Console.StyleParser.Parse(String text) in /_/src/Spectre.Console/StyleParser.cs:line 10
   at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 22
   at Spectre.Console.Markup..ctor(String text, Style style) in /_/src/Spectre.Console/Widgets/Markup.cs:line 42

**Expected behavior**
The code working with 0.44 should also work with 0.45.

**Comment by nils-a** [comment]
Could be a regression from #911. I'll have a look at it.

**Comment by majorregal** [comment]
Hello, I'm having the exact same issue with this code:
```cs
private static void WriteLine(string message)
{
	AnsiConsole.MarkupLine($"[red][[[/]{DateTime.Now:yyyy-MM-dd HH:mm:ss.fff}[red]]][/] {message}");
}
```

**Comment by patriksvensson** [comment]
@majorregal What (exact) version of Spectre.Console?

**Comment by majorregal** [comment]
@patriksvensson Sorry, using `0.45.0`.

**Comment by patriksvensson** [comment]
I think @nils-a already fixed this so if you could reference the latest preview of Spectre.Console and verify that it is fixed, it would be great.

**Comment by nils-a** [comment]
@patriksvensson if you're thinking about https://github.com/spectreconsole/spectre.console/pull/1027, that one is not merged. :-)

But that gives me the opportunity to add the above problem to the unit tests.

**Comment by nils-a** [comment]
@patriksvensson You were right, I fixed it (well, in the PR). The problem above is precisely my first test case: `"[white][[[/][white]]][/]"`. I rebased the PR.
