### ISSUE TITLE
JSON Syntax Highlighting Support In Console

### ISSUE THREAD

**Issue by sangeethnandakumar** [spectreconsole/spectre.console#1051]
### No way to colorize a custom code snippet like JSON in Console. It's difficult to manually do it with Markup

![image](https://user-images.githubusercontent.com/24974154/200365481-2d4e31a5-5119-4d6f-819c-5e1876858964.png)

A utility class that can syntax highlight passed JSON and returns a Markup instance
Any easy mechanism. Can be a separate NuGet package with extensions to support many languages, constructs etc...

At times we may need to show JSON in console. Rather showing RAW JSON, SpecreConsole can format it with markups for syntax highlighting

**Comment by nils-a** [comment]
There has been some discussions around this in https://github.com/spectreconsole/spectre.console/discussions/820

Maybe, since the release of https://www.nuget.org/packages/LitJson.Source/0.19.0-alpha0027 someone could give it a try without a hard dependency to an external JSON parser.

**Comment by patriksvensson** [comment]
To be honest, I don't think it's necessary to take a dependency on a JSON library at all since parsing it into tokens is very straight forward. I could take a stab at this if you want to (I have some time to kill this evening).
