### ISSUE TITLE
Prompt Cancellation is broken

### ISSUE THREAD

**Issue by azchohfi** [spectreconsole/spectre.console#1076]
**Information**
 - OS: Windows
 - Version: 0.45.0
 - Terminal: Windows Terminal

**Describe the bug**
Issue #417 mentions that cancellation should be supported, and PR #477 is said to fix it, but it you, for example, press Ctrl+C while selecting items from a list, the process gets stuck. 

I debugged the source, and I believe I found the root cause.
This is the only line of code that checks for cancellation, at all, and this is correct:
https://github.com/spectreconsole/spectre.console/blob/52c1d9122bce4c73ae9205e2f2aff01cba03a4c4/src/Spectre.Console/Internal/DefaultInput.cs#L41-L44

The problem is that the SelectionPrompt, and likely all other Prompts, are doing this:
https://github.com/spectreconsole/spectre.console/blob/a9b97fa4dc0e868e1835b91ceed3641085d282ae/src/Spectre.Console/Prompts/List/ListPrompt.cs#L49-L54

They should **_also_** check for the cancellation of the cancellation token before they call the underlying method.

**To Reproduce**
```c#
await new SelectionPrompt<T>()
...
    .AddChoices(choices)
    .ShowAsync(AnsiConsole.Console, ct)
```
Then simply cancel the cancellation token `ct`, and the process will get stuck.

**Expected behavior**
The SelectionPrompt.ShowAsync(...) method should return when the cancellation token is cancelled.

**Comment by GOATS2K** [comment]
Any updates? This is still an issue.

**Comment by patriksvensson** [comment]
No one has submitted a PR for this yet.

**Comment by 0xced** [comment]
Is this still an issue with Spectre.Console version 0.47.0? I have tested with the following sample program and pressing Ctrl + C works as expected and the app exits by printing `Choosing size was canceled`.

**Sample.csproj**
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console.Cli" Version="0.47.0" />
  </ItemGroup>

</Project>
```

**Program.cs**
```cs
using System;
using System.Threading;
using Spectre.Console;

var cts = new CancellationTokenSource();
Console.CancelKeyPress += (_, args) =>
{
    args.Cancel = true;
    cts.Cancel();
};

try
{
    var size = await new SelectionPrompt<Size>().AddChoices(Enum.GetValues<Size>()).ShowAsync(AnsiConsole.Console, cts.Token);
    AnsiConsole.Console.MarkupLineInterpolated($"The {size} size was chosen");
    return 0;
}
catch (OperationCanceledException)
{
    AnsiConsole.Console.WriteLine();
    AnsiConsole.Console.WriteLine("Choosing size was canceled");
    return 1;
}
catch (Exception exception)
{
    AnsiConsole.Console.WriteException(exception);
    return 2;
}

internal enum Size
{
    Small,
    Medium,
    Large,
}
```

**Comment by caesay** [comment]
Is an issue for me with TextPrompt. It's intermittent. The following code for me only throws an OperationCanceledException about half the time. The rest of the time it just hangs indefinitely. 

```cs
        public async Task<bool> PromptYesNo(string prompt, bool? defaultValue = null, int? msTimeout = null)
        {
            var def = defaultValue ?? defaultFactory.DefaultPromptValue;
            var cts = new CancellationTokenSource();
            cts.CancelAfter(msTimeout ?? 11_000);

            var cp = new ConfirmationPrompt("[underline bold orange3]QUESTION:[/]" + Environment.NewLine + prompt) {
                DefaultValue = def,
            };
            try {
                AnsiConsole.WriteLine();
                var result = await cp.ShowAsync(AnsiConsole.Console, cts.Token).ConfigureAwait(false);
                AnsiConsole.WriteLine();
                return result;
            } catch (OperationCanceledException) {
                AnsiConsole.Write($" Accepted default value ({def}) because the prompt timed out." + Environment.NewLine + Environment.NewLine);
                return def;
            }
        }
```
