### ISSUE TITLE
Problem Rendering € sign

### ISSUE THREAD

**Issue by pitermarx** [spectreconsole/spectre.console#1092]
**Information**
 - OS: Windows
 - Version: 0.45/dotnet 7
 - Terminal: Windows Terminal/Integrated vscode/Command Prompt

**Describe the bug**
The € sign appears as ?

![image](https://user-images.githubusercontent.com/3081298/203968442-99028fce-8aa7-4bd8-a69e-c382617df77a.png)

**Additional context**
I'm hoping this is a problem on my end, but I'm out of ideas

**Comment by pitermarx** [comment]
This is surely a problem on my side
![image](https://user-images.githubusercontent.com/3081298/203974968-cdb51882-3396-4e73-807b-7a5ee35779d3.png)

**Comment by pitermarx** [comment]
Doing this on Powershell solves it
```powershell
[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
```

doing this on the app also solves it
```cs
Console.OutputEncoding = System.Text.Encoding.UTF8;
```

It used to work before for me, not sure what changed...
I will close this

**Comment by patriksvensson** [comment]
Hmmm, I would want to re-open this issue if it's OK. Since we're not changing the encoding, it should be OK.

**Comment by patriksvensson** [comment]
The `€` character is a Unicode character, and for some reason, the terminal seems to have the correct encoding but not the process.
