### ISSUE TITLE
AnsiConsole.Status().Spinner has been set to different known Spinner, but always use LineSpinner

### ISSUE THREAD

**Issue by shiaharfiyan** [spectreconsole/spectre.console#1100]
**Information**
 - OS: Windows 11
 - Version: 22H2 (22621.819)
 - Terminal: Windows Terminal v1.15.2875.0

**Describe the bug**
Try to use different known spinner for status, but when running the app, it always use LineSpinner

**To Reproduce**
Normal way to reproduce:
```CSharp
await AnsiConsole.Status()
    .Spinner(Spinner.Known.Aesthetic)
    .StartAsync("Loading...", async ctx =>
    {
        await Task.Delay(50000);
        AnsiConsole.WriteLine("hello");
    });
```

**Expected behavior**
Status use spinner set by user

**Screenshots**
![image](https://user-images.githubusercontent.com/62987279/205947061-deb1e735-977c-4dea-8054-f13c5ba271fb.png)

**Additional context**

**Comment by shiaharfiyan** [comment]
Status also generate 1 empty row above..
![image](https://user-images.githubusercontent.com/62987279/205947781-ea35d4de-0d39-48c9-a989-14a3a0579910.png)

**Comment by patriksvensson** [comment]
This happens because your terminal stdout doesn't have a unicode encoding. Read more here: https://spectreconsole.net/best-practices

**Comment by shiaharfiyan** [comment]
Yes, my bad.

Thank you.

**Comment by silkfire** [comment]
> Status also generate 1 empty row above.. ![image](https://user-images.githubusercontent.com/62987279/205947781-ea35d4de-0d39-48c9-a989-14a3a0579910.png)

@patriksvensson As per this comment, is there a way to remove the initial empty line when using Status?
