### ISSUE TITLE
TypeRegistrar should be public

### ISSUE THREAD

**Issue by scosec** [spectreconsole/spectre.console#1110]
**Information**
 - .Net Core
 - Version: 6.0

**Describe the bug**
The typeregistrar should be a public class. If you follow the example from the documentation with dependency injection it doesn't work because the class is internal and can't be used outside the namespace.

**To Reproduce**
Copy the documentation example with dependency injection.

**Expected behavior**
Allow usage for the TypeRegistrar

**Screenshots**
![spectre](https://user-images.githubusercontent.com/14801619/206997336-753a42a0-787a-4bbe-af76-7ade526c08cb.png)

**Comment by patriksvensson** [comment]
TypeRegistrar should not be made public. It's just used internally if no custom type-registrar is available. We should update the documentation.

**Comment by scosec** [comment]
Ah oke, I will create my own then! Thanks for the quick reply!

**Comment by nils-a** [comment]
@scosec, if you need a prebuild TypeRegistrar, you can have a look at 

- https://www.nuget.org/packages/Spectre.Console.Extensions.Hosting,
- https://www.nuget.org/packages/Spectre.Console.Registrars.Microsoft-Di or
- https://www.nuget.org/packages/Spectre.Console.Registrars.SimpleInjector

**Comment by patriksvensson** [comment]
@scosec Thank you! What episode was that if I might ask?

**Comment by scosec** [comment]
@patriksvensson they mentioned it in the last episode wolverine.net command and messagebus with jeremy miller.
