### ISSUE TITLE
Remove push to GitHub Packages

### ISSUE THREAD

**Issue by patriksvensson** [spectreconsole/spectre.console#1114]
I suggest we remove GitHub packages for Spectre.Console since it literally had 0 downloads since we added it.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/357872/208298638-8105700e-44be-4154-a520-63839bbcf90a.png">

**Comment by nils-a** [comment]
Yes, one needs to be signed in and have access to the feed to use it. 
I have the feeling GPR is rather unusable for most cases.

**Comment by 0xced** [comment]
Back when the _GitHub Support Community_ was still a thing, a very long thread named [Download from Github Package Registry without authentication](https://github.community/t/download-from-github-package-registry-without-authentication/14407/90) was full of people complaining about the authentication requirement for public packages. This URL now redirects to the [GitHub Community Discussions](https://github.com/orgs/community/discussions/) homepage. There, you'll find another round of issues with people looking for a solution without authentication but ultimately that's still not possible.

* [How to make Github packages to the public](https://github.com/orgs/community/discussions/25629)
* [How to allow unauthorised read access to GitHub packages maven repository?](https://github.com/orgs/community/discussions/26634)
* [NPM public packages can't be accessed without a token](https://github.com/orgs/community/discussions/33875)
* [Why Do We Need to Authenticate to Download/Read Ruby Gems?](https://github.com/orgs/community/discussions/38681)

So yes, more than 3 years after its introduction, the GitHub Package Registry is still pretty much useless for open source projects. ¯\\\_(ツ)_/¯

(I also tried to publish a NuGet package of mine on GitHub Package Registry last year and deleted everything when I realised that requiring a complicated authentication setup would mean nobody would use it, not even myself.)

**Comment by nils-a** [comment]
This was resolved in https://github.com/spectreconsole/spectre.console/commit/383bee0e3e0ffb9bcadc2071018a40811600a02e
