### ISSUE TITLE
AnsiConsole.WriteLine(string) does not wrap text the same way as System.Console.WriteLine()

### ISSUE THREAD

**Issue by ashscodes** [spectreconsole/spectre.console#1122]
**Information**
 - OS: Windows 10 and Ubuntu 22.04 (WSL)
 - Version: 0.45.0
 - Terminal: Windows Terminal

**Describe the bug**

Firstly, thanks for making a great project available. The amount of detail that has gone in to it is fantastic and it is enjoyable to use.

I am not sure if this is by design or if I am doing something wrong, but when I have a long string and I have used `AnsiConsole.WriteLine(string)`, the console doesn't wrap the text as `System.Console.WriteLine(string)` does. I noticed this because I have a CLI option that returns a JSON string from one utility and reads it as standard input in another, but when the text doesn't wrap with the console properly, then it sees it as separate strings.

**To Reproduce**

Create a new project:

```
mkdir AnsiConsole.Test
dotnet new console -n AnsiConsole.Test -o .\AnsiConsole.Test\
dotnet add .\AnsiConsole.Test\ package Spectre.Console
```

Replace the code in `Program.cs` with:

```csharp
// See https://aka.ms/new-console-template for more information
using Spectre.Console;

string normal = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum";
string testJson = "{\"id\":\"some-id\",\"description\":\"If my string is longer than the console width, AnsiConsole.WriteLine seems to split my console output at the end of this description, but System.Console.WriteLine will not.\",\"data\":[{\"name\":\"Test1\",\"id\":1,\"href\":\"https://test1.link\"},{\"name\":\"Test2\",\"id\":2,\"href\":\"https://test2.link\"},{\"name\":\"Test3\",\"id\":3,\"href\":\"https://test3.link\"},{\"name\":\"Test4\",\"id\":4,\"href\":\"https://test4.link\"},{\"name\":\"Test5\",\"id\":5,\"href\":\"https://test5.link\"},{\"name\":\"Test6\",\"id\":6,\"href\":\"https://test6.link\"},{\"name\":\"Test7\",\"id\":7,\"href\":\"https://test7.link\"},{\"name\":\"Test8\",\"id\":8,\"href\":\"https://test8.link\"},{\"name\":\"Test9\",\"id\":9,\"href\":\"https://test9.link\"},{\"name\":\"Test10\",\"id\":10,\"href\":\"https://test10.link\"},{\"name\":\"Test11\",\"id\":11,\"href\":\"https://test11.link\"},{\"name\":\"Test12\",\"id\":12,\"href\":\"https://test12.link\"},{\"name\":\"Test13\",\"id\":13,\"href\":\"https://test13.link\"},{\"name\":\"Test14\",\"id\":14,\"href\":\"https://test14.link\"},{\"name\":\"Test15\",\"id\":15,\"href\":\"https://test15.link\"},{\"name\":\"Test16\",\"id\":16,\"href\":\"https://test16.link\"},{\"name\":\"Test17\",\"id\":17,\"href\":\"https://test17.link\"},{\"name\":\"Test18\",\"id\":18,\"href\":\"https://test18.link\"},{\"name\":\"Test19\",\"id\":19,\"href\":\"https://test19.link\"},{\"name\":\"Test20\",\"id\":20,\"href\":\"https://test20.link\"}],\"name\":\"Hello World\"}";
System.Console.WriteLine(normal);
System.Console.WriteLine();
AnsiConsole.WriteLine(normal);
System.Console.WriteLine();
System.Console.WriteLine(testJson);
System.Console.WriteLine();
AnsiConsole.WriteLine(testJson);
```

Run the project:

```
dotnet run --project .\AnsiConsole.Test\
```

**Expected behavior**
Behaviour similar to that of `System.Console.WriteLine()` i.e. The text wraps mid word and doesn't wrap because the next value is too long for the remaining text in the buffer.

**Screenshots**

![image](https://user-images.githubusercontent.com/70372500/210527234-0344fcd1-5b78-47b6-8e8a-ffffb41bc46d.png)

**Additional context**

Of course I can just use `System.Console.WriteLine()` to return the string, however I think this should be looked at as I expect most people will be anticipating that they will be getting a drop in replacement and get the same result when using `AnsiConsole.WriteLine()`.

As an aside, but related, if I use `AnsiConsole.Write(string)` an error is thrown with the JSON as the string only overload is passed on for formatting elsewhere and the JSON braces cause it to throw an invalid format error. I believe this came up in another issue for the `Markup` class, but I can't find it right now.

**Comment by patriksvensson** [comment]
@ashscodes Thanks for reporting this, but word wrapping like this is by design. `AnsiConsole.WriteLine` was not designed to be a drop-in for `Console.WriteLine`.

We could perhaps add an option to the `Paragraph` widget to disable word wrapping and allow the consumer to use that instead.

**Comment by ashscodes** [comment]
Okay, I had a feeling that it might be by design, probably due to the buffer created for the console.

I guess if it is by design then the an additional option is not required, however, perhaps it might be worth documenting a quick line that states `AnsiConsole.Write` and `AnsiConsole.WriteLine` are synonymous with the `Console` equivalents, because although I thought that might be the answer, I think others may assume that the methods might work similarly. I don't need to use it and can just switch to `Console` though.

I will log a separate issue for the error being thrown by `AnsiConsole.Write(string)` if you would like? (At the bottom of the OP)

**Comment by patriksvensson** [comment]
@ashscodes Would be great if you log a separate issue for that. Thanks! 👍

**Comment by ashscodes** [comment]
Thanks for the quick responses, Patrik!
