### ISSUE TITLE
[Help] Is it possible to return the index of selection instead of its value ?

### ISSUE THREAD

**Issue by Enissay** [spectreconsole/spectre.console#1134]
I am new to this library and could not figure out how to "show something" in the selection list (which can be user friendly), and return "something else" when it is selected (non user friendly: index, key).

The value to return could be the index from a list of choices OR a key from a dictionary.

For instance, how to transform the example below to return the key rather than the fruit value/name:

```c#
var fruits = new Dictionary<string, string>
{
    {"first", "Apple"},
    {"second", "Apricot"},
    {"third", "Avocado"},
};
```

https://spectreconsole.net/prompts/selection
```c#
// Ask for the user's favorite fruit
var fruit = AnsiConsole.Prompt(
    new SelectionPrompt<string>()
        .Title("What's your [green]favorite fruit[/]?")
        .PageSize(10)
        .MoreChoicesText("[grey](Move up and down to reveal more fruits)[/]")
        .AddChoices(new[] {
            "Apple", "Apricot", "Avocado"
        }));

// Echo the fruit back to the terminal
AnsiConsole.WriteLine($"I agree. {fruit} is tasty!");
```
Of course one way could be adding an extra check to find and retrieve the value from the collection based on the selection BUT I wonder if that is already built in ?

**Comment by patriksvensson** [comment]
@Enissay no, that's not possible. Since selections can be divided into groups (https://spectreconsole.net/api/spectre.console/selectionpromptextensions/fc01d246) there is no index of each item that always correspond to the input.

A workaround could be creating a custom object that holds an index, and use a converter for the display value.
