### ISSUE TITLE
Incorrect Code Example Documentation: Justification invocations

### ISSUE THREAD

**Issue by mlasker** [spectreconsole/spectre.console#1137]
**Information**
n/a

**Describe the bug**
Code example documentation is incorrect for anything with extension methods for justification (at least on my version). For example, [the documentation for grid](https://spectreconsole.net/widgets/grid) shows this:

```
new Text("Header 1", new Style(Color.Red, Color.Black)).LeftAligned(),
new Text("Header 2", new Style(Color.Green, Color.Black)).Centered(),
new Text("Header 3", new Style(Color.Blue, Color.Black)).RightAligned()
```

But on my current version of 0.46.0 these generate compiler errors. The correct invocation appears to be 

```
new Text("Header 1", new Style(Color.Red, Color.Black)).LeftJustified(),
new Text("Header 2", new Style(Color.Green, Color.Black)).Centered(),
new Text("Header 3", new Style(Color.Blue, Color.Black)).RightJustified()
```

**Comment by mlasker** [comment]
Tried to look around for how to contribute to the website documentation but not sure. Would be happy to fix it if I am able to

**Comment by patriksvensson** [comment]
@mlasker Thanks for reporting this.

The files that has this error are from a first glance:

* https://github.com/spectreconsole/spectre.console/blob/main/docs/input/widgets/grid.md
* https://github.com/spectreconsole/spectre.console/blob/main/docs/input/widgets/table.md
* https://github.com/spectreconsole/spectre.console/blob/main/docs/input/widgets/text-path.md

... and probably more :smile:

Any help here is appreciated.

**Comment by patriksvensson** [comment]
@mlasker Assigned the issue to you. Tell us if you're not able to help out and I'll remove the assignment.

**Comment by patriksvensson** [comment]
Superseeded by #1144
