### ISSUE TITLE
Support for .NET NativeAOT

### ISSUE THREAD

**Issue by bsdayo** [spectreconsole/spectre.console#1155]
I'm trying to build a command line tool with `Spectre.Console.Cli` and .NET NativeAOT enabled in .NET 7 (by `<PublishAot>true</PublishAot>` in csproj). But when I publish this project I get the following warnings:
```
MSBuild version 17.4.1+9a89d02ff for .NET
  正在确定要还原的项目…
  所有项目均是最新的，无法还原。
  RenameX -> D:\Code\RenameX\RenameX\bin\Release\net7.0\win-x64\renx.dll
  Generating native code
C:\Users\b1acksoil\.nuget\packages\spectre.console.cli\0.46.1-preview.0.6\lib\net7.0\Spectre.Console.Cli.dll
: warning IL2104: Assembly 'Spectre.Console.Cli' produced trim warnings. For more information see https://aka
.ms/dotnet-illink/libraries [D:\Code\RenameX\RenameX\RenameX.csproj]
C:\Users\b1acksoil\.nuget\packages\spectre.console.cli\0.46.1-preview.0.6\lib\net7.0\Spectre.Console.Cli.dll
: warning IL3053: Assembly 'Spectre.Console.Cli' produced AOT analysis warnings. [D:\Code\RenameX\RenameX\Ren
ameX.csproj]
C:\Users\b1acksoil\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\7.0.2\framework\System.Private
.Xml.dll : warning IL3053: Assembly 'System.Private.Xml' produced AOT analysis warnings. [D:\Code\RenameX\Ren
ameX\RenameX.csproj]
C:\Users\b1acksoil\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\7.0.2\framework\System.Net.Htt
p.dll : warning IL3053: Assembly 'System.Net.Http' produced AOT analysis warnings. [D:\Code\RenameX\RenameX\R
enameX.csproj]
    正在创建库 bin\Release\net7.0\win-x64\native\renx.lib 和对象 bin\Release\net7.0\win-x64\native\renx.exp
  RenameX -> D:\Code\RenameX\RenameX\bin\Release\net7.0\win-x64\publish\
```

After I run the published exe I get the following error:

```
Error: Could not find a constructor for 'NekoSpace.RenameX.MainCommand'.
```

The minimal reproducable program is like this:

```csharp
using Spectre.Console;
using Spectre.Console.Cli;

var app = new CommandApp<MainCommand>();
return app.Run(args);

public sealed class MainCommand : Command
{
    public override int Execute(CommandContext context)
    {
        AnsiConsole.MarkupLine("[blue]Hello, world![/]");
        return 0;
    }
}
```

I think it will be amazing if this library could support NativeAOT, for faster startup speed, smaller packaged size, no runtime needed, etc.

**Comment by b1acksoil** [comment]
Not sure if this issue is related to trimming, because I tried to remove `<PublishAot>` and publish the project with
```
dotnet publish -c Release -r win-x64 --self-contained -p:PublishTrimmed=true
```
After running it I got the following error:
```
Unhandled exception. Spectre.Console.Cli.CommandRuntimeException: Could not get settings type for command of type 'NekoSpace.RenameX.MainCommand'.
   at Spectre.Console.Cli.ConfiguredCommand.FromType[TCommand](String, Boolean ) in /_/src/Spectre.Console.Cli/Internal/Configuration/ConfiguredCommand.cs:line 53
   at Spectre.Console.Cli.Configurator.SetDefaultCommand[TDefaultCommand]() in /_/src/Spectre.Console.Cli/Internal/Configuration/Configurator.cs:line 31
   at Spectre.Console.Cli.CommandApp.SetDefaultCommand[TCommand]() in /_/src/Spectre.Console.Cli/CommandApp.cs:line 48
   at Spectre.Console.Cli.CommandApp`1..ctor(ITypeRegistrar ) in /_/src/Spectre.Console.Cli/CommandAppOfT.cs:line 22
   at Program.<Main>$(String[]) in D:\Code\RenameX\RenameX\Program.cs:line 4
```

Seems to be the same with [this](https://github.com/spectreconsole/spectre.console/issues/955#issuecomment-1366052281)

**Comment by TomatoPuddin** [comment]
Create a xml file:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<linker>
  <assembly fullname="Spectre.Console" preserve="all" />
  <assembly fullname="Spectre.Console.Cli" preserve="all" />
  <assembly fullname="YourAssemblyName" preserve="all" />
</linker>
```

Add this section to csproj file:
```xml
<ItemGroup>
  <TrimmerRootDescriptor Include="path/to/the/xml" />
</ItemGroup>
```

Then try again.
Reference: [Trimming options](https://learn.microsoft.com/zh-cn/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0)

**Comment by bsdayo** [comment]
Thanks, that solved the problem.

**Comment by CyberSinh** [comment]
Support for .NET trimming should be native with `[AssemblyMetadata("IsTrimmable", "True")]`. The xml solution is just a workaround. Can we expect a more dev-friendly solution in future release? 
Thanks.

**Comment by baterja** [comment]
Hello there, I'm here for the same reason - publishing a trimmed app. I see the workaround is there, but the workaround is not to trim the library, so my app will carry its whole weight and it's not the goal of publishing trimmed apps :) So if you would ever like to make the library "trimmable", I'd be grateful :)

**Comment by ronnyek** [comment]
I too am looking into this. If I set `<PublishTrimmed>true</PublishTrimmed>` in my project, it does work... I just get trimming warnings, and it seems to indicate that its probably related to the fact that `Spectre.Console.Cli` uses reflection to gather metadata on commands. 

The app does start, though admittedly I haven't exhaustively tested any functionality

I'm wondering if in-fact that is the cause for trimming warnings, if reflection could be replaced with code generator and if so, would that actually result in significant differences in ultimate trimmed binaries.

**Comment by ronnyek** [comment]
Spoke too soon
```
Error: Could not resolve type 'Commands.UpgradeCommand+Settings'
```
