### ISSUE TITLE
USAGE comment seems to have an incorrect order

### ISSUE THREAD

**Issue by KeithMAtFis** [spectreconsole/spectre.console#1170]
When a Spectre Console CLI outputs its default help it seems that the USAGE: comment seems to have an incorrect order the wrong way around.

Maybe it is my understanding when the order is `[OPTIONS] <COMMAND>` the command is ignored, however with the order as `<COMMAND> [OPTIONS] `everything works as expected.

For example:

**my.exe /test -h** will display the help for the test command.
**my.exe -h /test** will just display the help.

Here is a screenshot of command line and suggested change area that will reorder the output:
![Untitled](https://user-images.githubusercontent.com/112524632/220004921-b95f5e61-7108-457b-95dc-81256d832739.jpg)

I am happy to be corrected if my understanding is incorrect.

Ta, Keith

**Comment by patriksvensson** [comment]
No, this is correct. Options are related to the current command and command settings. You can pass options to the current command and then branch off to another one, passing more options.

Consider

```
dotnet sln foo.sln add bar.csproj
```

Where `sln` is the first command, `foo.sln` is an argument (could be an option), and `bar` is another command, taking `bar.csproj` as an argument (could be an option).
