### ISSUE TITLE
Incorrect argument order displayed for command branches

### ISSUE THREAD

**Issue by ddagnew** [spectreconsole/spectre.console#1199]
**Information**
 - OS: [eg Windows/Linux/MacOS]
 - Version: [e.g. 0.33.0]
 - Terminal: [e.g Windows Terminal]

**Describe the bug**
If a command is defined within a command branch, then the summary for that branch will show arguments for the command in the order that their corresponding properties were defined, rather than according to their specified positions.  

**To Reproduce**
Create a command branch and a command within that branch.  Add multiple arguments to the command but don't order the declarations by their positions.  (We are ordering alphabetically).

**Expected behavior**
The branch summary orders the command arguments by their specified positions, not the order in which the properties were defined.

**Screenshots**
![image](https://user-images.githubusercontent.com/93213468/225459928-b742d9f8-d418-4488-b4c6-0ae300260b21.png)
![image](https://user-images.githubusercontent.com/93213468/225459992-f43d258c-3b74-4e83-b192-bfef16b8b4fc.png)

**Additional context**

**Comment by nils-a** [comment]
I can no longer reproduce this error with the current version `0.47.0`, so I'm going ahead and close this issue.
@ddagnew if the issue persists for you, I'll reopen this.
