### ISSUE TITLE
Command line tab completion or suggestion

### ISSUE THREAD

**Issue by pwm1234-sri** [spectreconsole/spectre.console#1201]
I would like to use spectre.console and spectr.console.cli but it seems to be missing command line completion capabilities. I have been using System.CommandLine but I see a lot in spectre that makes me want to try it out. But I do not want to lose the command-line completion capabilities that I get with System.CommandLine and dotnet-suggest.  Is command line completion on the roadmap for spectre.console.cli? I appreciate your time.

**Comment by phil-scott-78** [comment]
It's been in discussion with #267. There has been a few people taking a stab at it, but not a ton of progress. So it's still up for grabs if anyone wants to get after it.

**Comment by pwm1234-sri** [comment]
Thanks! I had seen that issue, but it seems to have fizzled out.
