### ISSUE TITLE
Export strings to .resx file to allow localization

### ISSUE THREAD

**Issue by CyberSinh** [spectreconsole/spectre.console#1213]
Hardcoded strings like **USAGE**, **OPTIONS**, **COMMANDS**, etc. should be extracted and stored in `.resx` file to allow localization.
I am ready to help by translating strings in French.
Regards,

**Comment by Psychlist1972** [comment]
I'm interested in a way to provide the strings to these. 
1. All caps doesn't really fit the aesthetic for the app we're working on
2. I'd like to change the color from Yellow.
3. I need to localize anything that can be localized.

So as long as there's a property or a function I can supply a markup string to, I'd be happy there.

**Comment by patriksvensson** [comment]
I suspect this will be resolved once #1852 lands.

**Comment by CyberSinh** [comment]
#1852 returns 404 error.

**Comment by patriksvensson** [comment]
Sorry #1259

**Comment by FrankRay78** [comment]
Hello @CyberSinh, would commandline switches also need localising?  eg. `applicationname --help` becomes `applicationname --aide` ?

**Comment by CyberSinh** [comment]
Hello @FrankRay78,
I don't think it's necessary to localize the names of the commands and options that are traditionally universal (= English) in command-line programs.

**Comment by FrankRay78** [comment]
@patriksvensson  Whilst https://github.com/spectreconsole/spectre.console/pull/1259 will centralise all the help strings into a single class that can be overrridden (`Spectre.Console.Cli.HelpHelpProvider`), I also like the idea of potentially supporting localisation of the strings used in this class, rather than requiring users of Spectre.Console to implement their own localised version of the help provider (as it's a fairly common use case, and also the help provider internal logic is rather involved for a casual user).

**Comment by FrankRay78** [comment]
Hello @Psychlist1972, any idea or suggestions as to the best implementation approach for customising the rendered colours? (short of completely overriding the help provider class and injecting it via DI). 

For context, here's a representative snippet illustrating how the current colour scheme is set:

```csharp
    public virtual IEnumerable<IRenderable> GetUsage(ICommandModel model, ICommandInfo? command)
    {
        var composer = new Composer();
        composer.Style("yellow", "USAGE:").LineBreak();
        composer.Tab().Text(model.ApplicationName);

        var parameters = new List<string>();

        if (command == null)
        {
            parameters.Add("[grey][[OPTIONS]][/]");
            parameters.Add("[aqua]<COMMAND>[/]");
        }
```

**Comment by patriksvensson** [comment]
I rather see the community implement localization support to be honest when we provide a extension point.

**Comment by FrankRay78** [comment]
> I rather see the community implement localization support to be honest when we provide a extension point.

💯 for community implementation

I fear, however, the way I implemented the extension point for custom help providers is heavy-handed for the simple case of localised strings (ie. I basically refactored the previous internal help writer and exposed the existing logic, with hard-coded strings and colours still in place).

Anyhow, lets get https://github.com/spectreconsole/spectre.console/pull/1259 over the line and then see what happens next...

**Comment by CyberSinh** [comment]
I agree with @FrankRay78, the main translations should be provided natively with Spectre.

The community will be able to help provide the translations which will then benefit all users.

Having to implement an extension point just to translate a few strings also seems to me far too cumbersome (+ risk of bug) for such a simple and common need.

**Comment by FrankRay78** [comment]
Ok @CyberSinh, I'm sufficiently interested in implementing this on a branch to see what it looks like.

I've gone through the current help provider and found the following hardcoded string literals:

Prints help information
Prints version information
DESCRIPTION
USAGE
OPTIONS
COMMAND
COMMANDS
EXAMPLES
ARGUMENTS
DEFAULT

Are you able to provide the french equivalents for me?

**Comment by CyberSinh** [comment]
Of course, here they are:

Prints help information -> Affiche les informations d'aide
Prints version information -> Affiche les informations de version
DESCRIPTION -> _idem_
USAGE -> _idem_
OPTIONS -> _idem_
COMMAND -> COMMAND**E**
COMMANDS -> COMMAND**E**S
EXAMPLES -> EX**E**MPLES
ARGUMENTS -> _idem_
DEFAULT -> D**É**FA**UT**

Thanks!

**Comment by FrankRay78** [comment]
Give me a week or two @CyberSinh.

**Comment by FrankRay78** [comment]
**Update** - I've started implementing this now.

**Comment by FrankRay78** [comment]
Hello @CyberSinh, perhaps you could road test the following, if you get a chance: https://github.com/spectreconsole/spectre.console/pull/1349

**Comment by CyberSinh** [comment]
Hi @FrankRay78, everything shown on the above screenshot is correct in French.
Thanks!
