### ISSUE TITLE
'Measure' in type 'Spectre.Cli.Internal.Composer' does not have an implementation.

### ISSUE THREAD

**Issue by codeConcussion** [spectreconsole/spectre.console#1222]
**Information**
 - OS: Windows
 - Version: Spectre.Console: 0.46.0, Spectre.Cli: 0.49.0
 - Terminal: Windows Terminal

**Describe the bug**
I'm trying to convert an old project to the newest version. I can execute commands without error but I get the error in the title when I try to display help using `--help` or `-h`

**Expected behavior**
I simply want help to display

**Additional context**
Using Autofac for DI.

**Comment by patriksvensson** [comment]
Somewhere in your project you have a reference to a Spectre.Console version lower tham 0.46. Make sure all versions are set to 0.46.

**Comment by codeConcussion** [comment]
Here are the references from my csproj file...
```
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="7.0.0" />
    <PackageReference Include="Spectre.Cli" Version="0.49.0" />
    <PackageReference Include="Spectre.Console" Version="0.46.0" />
    <PackageReference Include="Spectre.Console.Json" Version="0.46.0" />
  </ItemGroup>
```

And here are the Spectre assemblies in my bin folder...
![Capture](https://github.com/spectreconsole/spectre.console/assets/651287/7b090857-fbbe-47f7-96ce-3e3ab378f235)

**Comment by patriksvensson** [comment]
Spectre.Cli is deprecated. You should be using version 0.46 of Spectre.Console.Cli.

https://spectreconsole.net/cli/migration

**Comment by codeConcussion** [comment]
@patriksvensson Removing Spectre.Cli and deleting all my bin and obj folders seemed to fix it. Thank you for the insight.
