### ISSUE TITLE
Exception message

### ISSUE THREAD

**Issue by jchannon** [spectreconsole/spectre.console#1235]
**Information**
 - OS: [eg Windows/Linux/MacOS] MacOS
 - Version: [e.g. 0.33.0] 12.6.5
 - Terminal: [e.g Windows Terminal] iTerm

**Describe the bug**
In my command class I have the following

```csharp
 public MyCommand()
 {
        var builder = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json", optional: false)
            .AddJsonFile("appsettings.development.json", optional: true);

        var config = builder.Build();
        var connString = config.GetValue<string>("Mongo:ConnectionString");
        var databaseName = config.GetValue<string>("Mongo:DatabaseName");
        var collectionName = config.GetValue<string>("Mongo:EntityTracking:Collection");

        if (string.IsNullOrWhiteSpace(connString))
        {
            throw new Exception("Mongo connection string is not provided");
        }
}
```

If the appsettings file doesn't exist for example and throws an exception or the config value validation throws, the error message reported is `Error: Could not resolve type MyCommand`

I've seen the code tries to create a "pretty" error message but for some reason I don't get the exception message appearing in the console in this example.

**To Reproduce**
See above

**Expected behavior**
The exception message rendered to the console

**Screenshots**

**Additional context**

**Comment by 0xced** [comment]
Shouldn't this code be executed as part of the command `Execute` method instead of inside the constructor?

```csharp
public class MyCommand : Command<MyCommand.MySettings>
{
    private readonly IAnsiConsole _console;

    public class MySettings : CommandSettings
    {
    }

    public MyCommand(IAnsiConsole console)
    {
        _console = console ?? throw new ArgumentNullException(nameof(console));
    }

    public override int Execute(CommandContext context, MySettings settings)
    {
        var builder = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json", optional: false)
            .AddJsonFile("appsettings.development.json", optional: true);

        var config = builder.Build();
        var connString = config.GetValue<string>("Mongo:ConnectionString");
        var databaseName = config.GetValue<string>("Mongo:DatabaseName");
        var collectionName = config.GetValue<string>("Mongo:EntityTracking:Collection");

        if (string.IsNullOrWhiteSpace(connString))
        {
            throw new Exception("Mongo connection string is not provided");
        }

        // Actual business here

        return 0;
    }
}
```

**Comment by nils-a** [comment]
@jchannon This is by design. 

When you add the exception to the constructor, it is impossible for spectre.console to create the command. In this case, the message of the underlying (inner) exception is not shown to the user because it is normally a very technical description.

What you can do is, like @0xced said, move the exception into the `Execute` part. This way, you'll see the message of the exception as output to the user.
The alternatives to this are described in the [Exceptions section of the documentation](https://spectreconsole.net/cli/exceptions): Either use `PropagateExceptions()` or `SetExceptionHandler()`.
