### ISSUE TITLE
Emojis and special characters not displaying correctly

### ISSUE THREAD

**Issue by benpaulsen4** [spectreconsole/spectre.console#1278]
**Information**
 - OS: Windows 11
 - Version: 0.47.0
 - Terminal: Windows Terminal

**Describe the bug**
A Windows Terminal update a couple of months ago appears to have broken emoji and special character renderings in my application. They used to work perfectly on the exact same build of my app so I do not believe it is a change I have made. Not only will all emojis display as question marks `??`, but even non-emoji unicode characters like ▲ display as a question mark (albeit different from emoji question marks).

Running the app in the basic command prompt and I can see that the emojis still don't render (potentially to be expected?) but the special characters *do* render correctly. Running in a Linux terminal and all appears to function as expected.

**To Reproduce**
Make use of special characters raw in strings, or emojis with the `:name:` syntax and print to Windows Terminal.

**Expected behavior**
Emojis and special characters should display correctly in the modern Windows Terminal.

**Screenshots**
<img width="840" alt="Screenshot 2023-08-16 165422" src="https://github.com/spectreconsole/spectre.console/assets/108066763/fc1a525f-4689-4767-b6e8-a6018be8b561">
In the above you can see all emojis as `??` and the special character at the top (in green) displaying as the diamond question mark character instead of ▲.

**Additional context**
Not sure if this is relevant, but I have noticed that advanced formatting features like custom spinners and rounded table/panel corners have never worked in Windows Terminal. I have only ever seen these working in Linux.

If any more information is needed, please let me know and I'll be more than happy to help. Keep up the good work! 😄

**Comment by patriksvensson** [comment]
@benpaulsen4 The output encoding in your terminal doesn't support Unicode. Spectre.Console will fall back to use safe output for your encoding if it cannot determine that it can output Unicode characters. 

You can read more here: https://spectreconsole.net/best-practices
