### ISSUE TITLE
How to access TypeRegistrar()  ???

### ISSUE THREAD

**Issue by dlandi** [spectreconsole/spectre.console#1285]
This code on your documentation doesn't work because type registrar is an internal sealed class.

How do use the registrar dependency injection?

![image](https://github.com/spectreconsole/spectre.console/assets/3196088/20ecc6a9-ce10-4f56-8176-0ccc70e694c1)

**Comment by phil-scott-78** [comment]
The two paragraphs after your screenshot should point you in the right direction.

Implementation for each container is going to look different so we leave it up to the user you provide it 

There are a handful of nuget packages out there that implement it for different containers too if you go looking.
