### ISSUE TITLE
Rendering a table instead prints `...`

### ISSUE THREAD

**Issue by thomhurst** [spectreconsole/spectre.console#1316]
**Information**
 - OS: Linux
 - Version: 0.47.0
 - Terminal: GitHub Actions

**Describe the bug**
Rendering a table instead prints `...`

**To Reproduce**
No idea!

**Expected behavior**
The table to print correctly

**Additional context**
Go to this run: https://github.com/thomhurst/ModularPipelines/actions/runs/6305854041/job/17119996662#step:5:3174
or this run:
https://github.com/thomhurst/ModularPipelines/actions/runs/6311141907/job/17134552410
Expand `Run pipeline` and scroll to the bottom.
A table should be rendered but it just prints `...`

This only seems to affect Linux so far. Windows and Mac I haven't noticed it on yet.

My code to print the table is the `PrintResults` method of this class:
https://github.com/thomhurst/ModularPipelines/blob/main/src/ModularPipelines/Helpers/ProgressPrinter.cs

If you want to see an example of it working, here is it rendering fine in a Windows run:
https://github.com/thomhurst/ModularPipelines/actions/runs/6311277163/job/17134959985

**Comment by patriksvensson** [comment]
This has been fixed in https://github.com/spectreconsole/spectre.console/issues/361 and will be available in 0.48. If you want to test the functionality before that, you should be able to use a pre-release version.
