### ISSUE TITLE
UseRenderHook and ControlCode not available

### ISSUE THREAD

**Issue by AleVin76** [spectreconsole/spectre.console#1372]
**Information**
 - OS: Win11 Pro

I created a console project where I added the code from the Progress example, but the UseRenderHook and ControlCode elements are not available.

I attach the solution.
[ConsoleApp2.zip](https://github.com/spectreconsole/spectre.console/files/13439383/ConsoleApp2.zip)

**Comment by patriksvensson** [comment]
I'm moving this over to our Q/A discussion forum. We do not open attachee zip files, so you will need to create a github repository and link to that.
