### ISSUE TITLE
CLI: Can no longer use IEnumerable<InterfaceType> in the Registrar

### ISSUE THREAD

**Issue by SarahKonnild** [spectreconsole/spectre.console#1378]
**Information**
.NET 8, Spectre.Console.Cli v0.48

**Describe the bug**
We used to be able to have IEnumerable<InterfaceType> as part of our Command constructor definition, and register multiple different classes under the same interface type in the Registrar on our CommandApp, like this:

```
public class ExampleCommand(IEnumerable<IDependency> dependencies)
{
    // code
}
```

and the CommandApp setup would include this on the CommandApp's config:

```
config.Settings.Registrar.Register<IDependency, Dependency1>();
config.Settings.Registrar.Register<IDependency, Dependency2>();
```

It results in the following error when attempting to run the CommandApp: `Error: could not resolve type`

**To Reproduce**
Create a CommandApp that has two classes implementing the same interface, and inject those to the Command's constructor.

**Expected behavior**
In 0.47.0 it was possible to register multiple dependencies under the same interface, and expect enumerables of that interface in the constructor of the Command - all the dependencies would come through and be injected correctly. 

It is still possible to do this in .NET 8.

**Screenshots**
None

**Additional context**
We tried to inject a List<IDependency> but with no luck, as the dependencies in these classes wouldn't resolve from the DI container.

I will happily answer any clarifying questions.

**Comment by Ibmurai** [comment]
I do wonder why the standard .NET DI container is wrapped in Spectre.Console at all?
Why not just use it?
By masking it you are masking features of standard DI container, like validate on build.

**Comment by SarahKonnild** [comment]
Imma close this because @Ibmurai realized this wasn't actually an issue.

**Comment by patriksvensson** [comment]
@Ibmurai Sorry, I don't understand. What "standard .NET DI container" is wrapped within Spectre? We do not to my knowledge have a dependency for a DI container at all.

**Comment by patriksvensson** [comment]
@SarahKonnild Awesome! Could you elaborate on what the problem was and how they solved it? Did they encounter the problem when updating to 0.48.0? Thanks!

**Comment by SarahKonnild** [comment]
> @SarahKonnild Awesome! Could you elaborate on what the problem was and how they solved it? Did they encounter the problem when updating to 0.48.0? Thanks!

@patriksvensson it was a huuuuge DI container brain fart we had in the office, so it would've happened in any DI Container 😆 we just failed to provide all necessary parameters to the DI container 😆 

Thank you for being so fast to update to .NET 8, we greatly appreciate it!!!

**Comment by patriksvensson** [comment]
@SarahKonnild Ah, I know what you mean. Guilty of a few of these myself 😁

Thanks for the kind words!

**Comment by Ibmurai** [comment]
Hi @patriksvensson !

We generally have many hard to debug DI issues with Spectre based apps. 

I'm sorry about the "wrapped DI container comment". That was a misunderstanding from my side. 

I do not understand why you use a bespoke DI container though. The one in .NET (5, 6, 7 and 8) has a a lot of nice features we generally miss, such as validate on build and, from .NET 8, named services. 

Why not just use that one? :)

**Comment by patriksvensson** [comment]
Spectre.Console does not have a DI container. It has an adapter for DI containers which will allow you to use the DI container of your choice.

**Comment by Ibmurai** [comment]
By `new`ing a `TypeRegistrar`... that's true. 

I guess I just don't understand the need for that. 

Buy you are right. Sorry. 

I wonder if we can use https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceprovider?view=dotnet-plat-ext-8.0 and the constructor parameter annotation for keyed services then? Or of some of the adaptation "hides" this?

**Comment by patriksvensson** [comment]
TypeRegistrar is internal and can't be newed up.

**Comment by Ibmurai** [comment]
> TypeRegistrar is internal and can't be newed up.

So we're supposed to write our own wrapper of ServiceProvider, to use that?

As per the example here: https://spectreconsole.net/cli/commandapp

**Comment by nils-a** [comment]
@Ibmurai yes, alternatively you can use an existing 3rd party wrapper.
