### ISSUE TITLE
Simplify the list of functions display

### ISSUE THREAD

**Issue by BachiMjavanadze** [spectreconsole/spectre.console#1383]
Please add syntax sugar to make it easier to display the function list. 

This is my code:

```
void Foo() => Console.WriteLine("Foo");
void Do() => Console.WriteLine("Do");
void Bar() => Console.WriteLine("Bar");
List<Action> functions = [Foo, Do, Bar];

AnsiConsole.MarkupLine("[red]Run the Funvtion:[/]\n");
var chosenFunction = AnsiConsole.Prompt(
    new SelectionPrompt<Action>()
        .AddChoices(functions));

chosenFunction();
```

Actual console output:

![image](https://github.com/spectreconsole/spectre.console/assets/38082501/672a3871-feb2-4a9d-a3bb-d71c7a69dc27)

desired result:

![image](https://github.com/spectreconsole/spectre.console/assets/38082501/701c1394-1d97-46aa-9456-67b6fbabf7ba)

At the moment to achieve the desired result I use a `switch expression`.  Please simplify it.

I suggest additional behavior of `Spectre.Console`; If the collection represents the dictionary :

```
Dictionary<Action, string> funCtions = new()
{
  { Foo, "Get Data" },
  { Do, "Put Data" },
  { Bar, "Delete Data" }
};
```

then output should be:

![image](https://github.com/spectreconsole/spectre.console/assets/38082501/c17357a3-cc99-4421-bf00-4cb1ae5e7c0a)

**Comment by patriksvensson** [comment]
You will need to use the [UseConverter](https://spectreconsole.net/api/spectre.console/selectionpromptextensions/c6320835) method to convert the `Action` to a `String`.

**Comment by BachiMjavanadze** [comment]
> You will need to use the [UseConverter](https://spectreconsole.net/api/spectre.console/selectionpromptextensions/c6320835) method to convert the `Action` to a `String`.

Thanks for response. If you mean this:

```
var chosenFunction = AnsiConsole.Prompt(
    new SelectionPrompt<Action>()
        .AddChoices(functions)
        .UseConverter(action => action.Method.Name));
```
        
it gives strange result:

![image](https://github.com/spectreconsole/spectre.console/assets/38082501/380dd8c7-efb4-4d20-b006-7dfbf4bbf3aa)

**Comment by BachiMjavanadze** [comment]
Actually we don't need this:

`List<Action> functions = [Foo, Do, Bar];`

this is a solution:
```
void Foo() => Console.WriteLine("Foo");
void Do() => Console.WriteLine("Do");
void Bar() => Console.WriteLine("Bar");

Dictionary<Action, string> funCtions = new()
{
  { Foo, "Get Data" },
  { Do, "Put Data" },
  { Bar, "Delete Data" }
};

AnsiConsole.MarkupLine("[red]Run the Function:[/]\n");
var chosenFunction = AnsiConsole.Prompt(
    new SelectionPrompt<Action>()
        .UseConverter(func => funCtions[func])
        .AddChoices(funCtions.Keys));

chosenFunction();
```

Thanks!

**Comment by BachiMjavanadze** [comment]
solved
