### ISSUE TITLE
[DOCS] Website documentation is unusable on Firefox

### ISSUE THREAD

**Issue by SanaRinomi** [spectreconsole/spectre.console#1394]
**Information**
 - OS: Agnostic

**Describe the bug**
Website documentation completely unusable on Firefox.

**To Reproduce**
Open https://spectreconsole.net/ on Firefox, same result on both Ubuntu 23.04 and on Windows.

**Screenshots**
![image](https://github.com/spectreconsole/spectre.console/assets/16209282/0cdbaa3f-5cf8-4b16-b6fb-95b37ad5dd67)
![image](https://github.com/spectreconsole/spectre.console/assets/16209282/d8df875c-3416-4c86-9aa1-40f59a22a85a)

**Additional context**
I couldn't see a repository relating to the website, so I posted here in the hopes to either be pointed in the right direction on where to post this issue, or have it be possibly solved.

**Comment by patriksvensson** [comment]
Hmm, very strange. I'm using Firefox as my main browser on Windows and macOS, and I haven't been able to recreate this. Do you have any browser extensions active by any chance?

![CleanShot 2023-12-02 at 15 45 13@2x](https://github.com/spectreconsole/spectre.console/assets/357872/6e5db177-5ddf-44d2-93cf-593b4e2effef)

**Comment by nils-a** [comment]
Stock FF 120.0.1 on a Windows machine - no problems here.

![image](https://github.com/spectreconsole/spectre.console/assets/349188/159ddd58-4fc7-4e6a-94f9-05e1a18ceefd)
