### ISSUE TITLE
[BUG] Command with -v displays AppVersion instead of executing the command.

### ISSUE THREAD

**Issue by JKamsker** [spectreconsole/spectre.console#1400]
**Information**
 - OS: Windows 11
 - Spectre Version:  0.47.1-preview.0.26
 - Terminal: WT

**Describe the bug**
A regression occurred in Spectre.Console version 0.47.1-preview.0.26 where the command option "-v" is now being misinterpreted as a request for version information within command settings, rather than being recognized as a command argument, which was the correct behavior in version 0.47.1-preview.0.17.

**To Reproduce**
1. Create a command with a "-v" option in its settings.
2. Execute the command with the "-v" option followed by a value (e.g., `app command -v 1.2.3`).
3. The application displays version information instead of executing the command.

**Expected behavior**
The command should execute as intended when the "-v" option is provided, as it did in version 0.47.1-preview.0.17.

**Actual Behavior**
Starting from version 0.47.1-preview.0.26, the application displays the version information and the command is not executed.

**Additional context**
The PR [#1399](https://github.com/spectreconsole/spectre.console/pull/1399) tests this bug. When fixed, the test should succeed. (Failure happens in [Test Run](https://github.com/spectreconsole/spectre.console/actions/runs/7098152430/job/19319531851?pr=1399#step:4:2704) )

**Comment by FrankRay78** [comment]
I introduced the bug @JKamsker, unfortunately. I knew it was a breaking change, and flagged it as such, but I think the change in functionality is probably now best described as a regression. I'll add this to my stack to review/address.

**Comment by FrankRay78** [comment]
FYI. I've submitted the PR above to revert this to existing behaviour @JKamsker
