### ISSUE TITLE
AnsiConsole.Ask has problem with inputting wide characters

### ISSUE THREAD

**Issue by ilyfairy** [spectreconsole/spectre.console#1406]
**Information**
 - OS: Windows
 - Version: [e.g. 0.48.0]
 - Terminal: Windows Terminal and cmd

AnsiConsole.Ask has problem with inputting wide characters.
Deleting will only delete half, and will result in the inability to delete the entire text in the input box.

```cs
var name = AnsiConsole.Ask<string>("What's your [green]name[/]?"); // 
Console.WriteLine(name);
```

**Expected behavior**
Ability to delete text normally

**Screenshots**
![VsDebugConsole_bBtIoBKiZD](https://github.com/spectreconsole/spectre.console/assets/52264192/2ee7cdad-5022-4a20-9d83-585371687094)

---
Please upvote :+1: this issue if you are interested in it.

**Comment by TonWin618** [comment]
this issue still exists. is there a workaround?

**Comment by TonWin618** [comment]
I noticed that the program did not account for character width when handling the Backspace key. I will open a PR later to fix this issue.
