### ISSUE TITLE
Would it be possible to condition the build-only PackageReferences?

### ISSUE THREAD

**Issue by baronfel** [spectreconsole/spectre.console#1421]
Hi! I am trying to get Spectre.Console added to the [dotnet/source-build-externals repo](https://github.com/dotnet/source-build-externals/pull/244) so that the SDK and MSBuild can take references to it in ways that work with our Linux Source Build partners' support lifecycles.  As a part of that, I have a patch that comments out a number of [build-metadata-related packages](https://github.com/spectreconsole/spectre.console/blob/6f1f29967da73938997fa8d2646bdc534721e04b/src/Directory.Build.props#L34C1-L43C15), but patches like this are fragile. Would you all be amenable to a solution where a property is checked in a Condition on this ItemGroup, and then the source-build-externals build of Spectre.Console could pass that property? If so, I'd be happy to contribute that.

**Comment by patriksvensson** [comment]
@baronfel Sure, sounds reasonble to me. We will happily accept a patch for this 🙂
