### ISSUE TITLE
Mandelbrot.cs contains code under GFDL 1.2

### ISSUE THREAD

**Issue by omajid** [spectreconsole/spectre.console#1423]
https://github.com/spectreconsole/spectre.console/blob/6f1f29967da73938997fa8d2646bdc534721e04b/examples/Console/Canvas/Mandelbrot.cs#L1-L4

I was looking to use Spectre.Console, but we found this file that's under GFDL 1.2.

You might already know this, but even Rosetta Code itself calls out that this is not a standard Open Source license:

> Exemptions
>
> From time to time, material on Rosetta Code is found to be useful in verbatim by programmers and authors. Being licensed under the GNU Free Documentation License, the material published on Rosetta Code is not compatible with most software licenses, including OSI-approved licenses such as the GPL. 

[Wikipedia](https://en.wikipedia.org/wiki/GNU_Free_Documentation_License) spells out that GFDL has several unusual conditions:

> - All previous authors of the work must be [attributed](https://en.wikipedia.org/wiki/Attribution_(copyright)).
> - All changes to the work must be logged.
> - All [derivative works](https://en.wikipedia.org/wiki/Derivative_work) must be licensed under the same license.
> - The full text of the license, unmodified invariant sections as defined by the author if any, and any other added warranty disclaimers (such as a general disclaimer alerting readers that the document may not be accurate for example) and copyright notices from previous versions must be maintained.

I don't think this project is meeting these requirements. In particular, the viral-GPL-like nature of this copyleft license also conflicts with the MIT license of this project, no?

Maybe you want to remove this file? Or replace it with a version based on an open source (MIT-compatible) license?

**Comment by patriksvensson** [comment]
Oh, I was under the impression that it was compatible. Will take a look at this when I have some spare time.
