### ISSUE TITLE
Repo doesn't seem to comply with GDFL

### ISSUE THREAD

**Issue by mthalman** [spectreconsole/spectre.console#1424]
The [Mandelbrot example](https://github.com/spectreconsole/spectre.console/blob/6f1f29967da73938997fa8d2646bdc534721e04b/examples/Console/Canvas/Mandelbrot.cs#L3C16-L3C46) makes use of code which is under the GNU Free Documentation License (GDFL). But the repo doesn't seem to comply with that license, specifically the Verbatim Copying section of the [license](https://www.gnu.org/licenses/old-licenses/fdl-1.2.html) that requires the license be reproduced.

This was originally discovered as part of the onboarding of this repo's code into the .NET SDK which would require all repo content to make use of free and open source licenses which the GDFL is not. For context, see https://github.com/dotnet/source-build-externals/pull/244 and https://gitlab.com/fedora/legal/fedora-license-data/-/issues/432. Ideally, this file would be removed from the repo to comply with free and open source licenses. If not, it should at least comply with the license requirements.

**Comment by patriksvensson** [comment]
Oh, I was under the impression that it was compatible. Will take a look at this when I have some spare time.
