### ISSUE TITLE
Pipe character for listing options e.g. `--option [RED|GREEN|BLUE]`

### ISSUE THREAD

**Issue by peteristhegreat** [spectreconsole/spectre.console#1434]
**Is your feature request related to a problem? Please describe.**
Right now, if I describe a CommandSetting with `[CommandOption("--option [RED|GREEN|BLUE]")]`, it fails with 

```
Error: An error occured when parsing template.
       Encountered invalid character '|' in value name.

       --option [RED|GREEN|BLUE]
                    ^ Invalid character
```
Likely caused by this line:
https://github.com/spectreconsole/spectre.console/blob/main/src/Spectre.Console.Cli/Internal/Configuration/TemplateParser.cs#L91

**Describe the solution you'd like**
I don't really expect the validation to use the list I put in the help text, but I would like it to allow the concise help to be able to show a list of acceptable answers instead of having to put it in the description.

**Describe alternatives you've considered**
I tried commas, and with angle brackets.

I think my next best workaround is something like:

```
[CommandOption("--option <RED_or_GREEN_or_BLUE>")]
```
or
```
[CommandOption("--option <COLOR>")]
[Description("Options for COLOR are RED, GREEN, or BLUE.")]
```

But both of the above doesn't seem quite as concise as my proposed solution of supporting the pipe character.

**Additional context**
If there is a better way to do this for this library, maybe seeing an example in the docs would be nice.

Also, thanks for the awesome library.  The docs are awesome, and I am loving the experience using it so far.

---
Please upvote :+1: this issue if you are interested in it.

**Comment by FrankRay78** [comment]
Hi @peteristhegreat, out of interest, what is the type for the color option?  ie. are these strings or Spectre.Console.Color or System.Drawing.Color

I ask, because it would be helpful to know.

I wonder if a similar thing for other values is/may be needed?  eg. allowable ints of 1, 5 or 10

I know we can do this with custom validation, but that's after the fact, and I'd like to look into this more with the premise of better supporting the input behaviour at the CommandOption definition

**Comment by peteristhegreat** [comment]
Good question..

Color was a generic example. In my use case it would always be a list of
valid strings the arg would take. Like an enum.

--output-file-type [YAML|JSON]

--account-type [FREE|HOBBY|PRO]

**Comment by FrankRay78** [comment]
As far as I can tell, the Option Value is for display purposes in the command help (ie. when `-h` or `--help` is run), and so I cannot see any reason as to why the pipe command shouldn't be allowed. 

Any validation of the actual allowable values entered on the command line can be done through validators, as per above.

This looks to me as the offending line, preventing the pipe delimiter being used:

https://github.com/spectreconsole/spectre.console/blob/e66d3aab2ea41afe2e31f7ae1fb5fe1e77821455/src/Spectre.Console.Cli/Internal/Configuration/TemplateParser.cs#L127
