### ISSUE TITLE
Blatant flickering

### ISSUE THREAD

**Issue by yenneferofvengerberg** [spectreconsole/spectre.console#1466]
**Information**
 - OS: Windows 10/11
 - Version: 0.48.0
 - Terminal: Dos Prompt, Powershell and Windows Terminal

**Describe the bug**
Displaying a task list with spinners causes the whole task list to flicker. Apparently, see below, this is a regression introduced in 0.48.0

**To Reproduce**
The following code exhibits the issue: (tested on .net 6.0 and .net 8.0)
```c#
using Spectre.Console;

namespace TestConsole
{
    internal static class Program
    {
        private static async Task LoopAsync(ProgressTask task)
        {
            await Task.Yield();

            for (int i = 0; i < 100; i++)
            {
                task.Increment(1);
                await Task.Delay(TimeSpan.FromSeconds(4)).ConfigureAwait(false);
            }
        }

        private static async Task Main()
        {
            Console.WriteLine("Flickering Test");

            var progress = AnsiConsole.Progress()
              .AutoRefresh(true)
              .AutoClear(false)
              .HideCompleted(false)
              .Columns(
              [
                  new TaskDescriptionColumn(),
                  new ProgressBarColumn(),
                  new PercentageColumn(),
                  new RemainingTimeColumn(),
                  new SpinnerColumn(Spinner.Known.Dots),
              ]);

            await progress.StartAsync(async x =>
            {
                var tasks = new List<Task>();
                for (int i = 0; i < 10; i++)
                {
                    var t = x.AddTask($"Task {i}", true, 100);
                    tasks.Add(LoopAsync(t));
                }

                await Task.WhenAll(tasks).ConfigureAwait(false);
            }).ConfigureAwait(false);
        }
    }
}

```
**Expected behavior**
No flickering, like in 0.47.0

**Screenshots**
**0.48.0**:
![Flickering](https://github.com/spectreconsole/spectre.console/assets/5850742/bd26b8a6-0ea0-4905-92d2-52e9186c4e92)
**0.47.0**:
![NoFlickering](https://github.com/spectreconsole/spectre.console/assets/5850742/a9efe7e1-0b35-472c-9d2b-d03027633ecc)

**Additional context**
The "regression" has been introduced in the commit https://github.com/spectreconsole/spectre.console/commit/71a5d830671220e601e4e6ab4d4c352ae0e0a64a

The offending line is in src/Spectre.Console/Live/LiveRenderable.cs:

```diff
-            return new ControlCode("\r" + CUU(linesToMoveUp));
+            return new ControlCode("\r" + (EL(2) + CUU(1)).Repeat(linesToMoveUp));
```

**Comment by ShaunLawrie** [comment]
This is also happening for other widget types in `0.48` including up to at least `0.48.1-preview.0.32` in Windows terminal

https://github.com/spectreconsole/spectre.console/assets/13159458/f2783bb7-08c5-49cd-a097-4bc06e78bea5

**Comment by GOATS2K** [comment]
This happens in progress displays without spinners as well.

**Comment by phil-scott-78** [comment]
Can confirm what @yenneferofvengerberg posted, rolling back that commit related to long lines smooths things out again. 

Probably need something a bit more clever than brute forcing a clear on each line each render. I'd almost be inclined to suggest using the `RenderHook` that now exists on `LiveRenderables` as the mechanism for including extra info while a progress is running rather than write line. Gives us a bit more control over the whole process too

**Comment by patriksvensson** [comment]
Is there a PR to roll this back?

**Comment by yenneferofvengerberg** [comment]
I considered doing it, but I couldn't figure out how to maintain the
correct behavior when the text goes out of screen. If someone can provide
me an hint, I would be happy to try

Op ma 1 apr 2024 13:41 schreef Patrik Svensson ***@***.***>:

**Comment by patriksvensson** [comment]
Since it's a regression I would say that it's OK with restoring it how it was, and look at finding a solution for it later.

**Comment by phil-scott-78** [comment]
Opened a PR for the revert https://github.com/spectreconsole/spectre.console/pull/1504

Regarding the original issue with WriteLine during a LiveRenderable, I wonder if some cleverness could be done to detect whether or not we can do the overwrite the content (no-flicker) vs erase what was written. Have to keep state of what was previously there on the last write, but I think it would be doable if someone had the gumption.
