### ISSUE TITLE
Remove System.Memory dependency from net 6+

### ISSUE THREAD

**Issue by thompson-tomo** [spectreconsole/spectre.console#1519]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
I want the package to not have an explicit dependency on System.Memory on net 6+. 

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/

---
Please upvote :+1: this issue if you are interested in it.

**Comment by patriksvensson** [comment]
@thompson-tomo Spectre.Console does not have a dependency on System.Memory on net6.0. It has a conditional dependency on that package for netstandard2.0.

![CleanShot 2024-04-17 at 01 29 58@2x](https://github.com/spectreconsole/spectre.console/assets/357872/54095258-1ae0-41fd-9840-088b3a854101)

**Comment by thompson-tomo** [comment]
Ahh, I had not checked the preview packages

**Comment by patriksvensson** [comment]
Hmm, we might actually need to investigate this. Seems like packaging doesn't respect the target version for some reason: https://www.nuget.org/packages/Spectre.Console/

![CleanShot 2024-04-17 at 09 51 58@2x](https://github.com/spectreconsole/spectre.console/assets/357872/79f926e7-726e-4fa9-a209-2bcadaeaba69)

**Comment by thompson-tomo** [comment]
Closing this as it is now not being included.
