### ISSUE TITLE
Progress update causes heavy flickering (regression from 0.47.0 to 0.48.0)

### ISSUE THREAD

**Issue by flobernd** [spectreconsole/spectre.console#1521]
**Information**
 - OS: Windows 11
 - Version: 0.48.0
 - Terminal: Windows Terminal

**Describe the bug**

Updating the progress of a `ProgressTask` casues heavy flickering.

**To Reproduce**

Run the example code that demonstrates the usage of `Progress`.

---
Please upvote :+1: this issue if you are interested in it.

**Comment by qubitz** [comment]
Was experiencing this issue and just upgraded to 0.49.1. Can confirm progresses (progressi?) are back to normal 👍.
