### ISSUE TITLE
Built-in parameter `--version` conflicts with existing one

### ISSUE THREAD

**Issue by sailro** [spectreconsole/spectre.console#1530]
**Information**
 - OS: `Windows`
 - Version: `Spectre.Console.Cli` v0.49.0
 - Terminal: `Windows Terminal / Oh My Posh` 

**Describe the bug**
Recent `Spectre.Console.Cli` versions fixed the issue with the new built-in `--version` parameter when _running_ the application, but we can still spot this one when using `--help`. My application is using `--version|-v` for a dedicated usage for years, so I don't want to see nor use the new `Prints version information` in the help menu. Is there a way to remove this ? Thanks ! 

**To Reproduce**
You can use:
https://github.com/sailro/DependencyPath
https://www.nuget.org/packages/DependencyPath#readme-body-tab
with the following command `dependency-path --help`

**Expected behavior**
I don't want to see a conflicting `--version` parameter with my own.

**Screenshots**
![image](https://github.com/spectreconsole/spectre.console/assets/638167/f01602c9-a482-47f3-8a04-0393c677950d)

**Additional context**
cc @FrankRay78 unfortunately, this simple little feature seems to be causing so many problems since its introduction.

Thanks !

---
Please upvote :+1: this issue if you are interested in it.

**Comment by patriksvensson** [comment]
There should be a version 0.49.1 out now. Let me know if that version solved this issue; otherwise, just reopen it.

**Comment by sailro** [comment]
Yes, I confirm this is working properly with 0.49.1. Thank you gain for quickly addressing this issue !

**Comment by Kampfmoehre** [comment]
Do we have to enable the built-in version feature now and how do we do it? With 0.49.1 the `--version` switch doesn o longer work, instead it prints out
```
Error: Unexpected option 'version'.

       --version
       ^^^^^^^^^ Did you forget the command?
```

**Comment by patriksvensson** [comment]
Use `config.UseAssemblyInformationalVersion()` to get auto versioning.

**Comment by samuel-lucas6** [comment]
`config.SetApplicationVersion()` and `config.UseAssemblyInformationalVersion()` didn't seem to work when I was testing 0.49.1. `-v|--version` didn't skip the `Validate` method like `-h|--help`, so I just got an error.

Then on 0.48.0, `-v|--version` prints a hex string after the version number on macOS:

```
$ application -v
1.0.0+6bc659b6988fe4317f8ce82c78f45b074606163f
```

I can't test whether this has been fixed on 0.49.1. If it hasn't, that should obviously be a separate issue.

**Comment by patriksvensson** [comment]
@samuel-lucas6 Could you provide a minimal reproducable example for this?

**Comment by samuel-lucas6** [comment]
> @samuel-lucas6 Could you provide a minimal reproducable example for this?

Sorry for not providing much detail. If you have a mandatory string `CommandOption` and do the following in `Validate(CommandContext context, Settings settings)`:

```c#
if (string.IsNullOrWhiteSpace(settings.StringOption)) {
    return ValidationResult.Error("string option must be specified.");
}
```

Then `-v|--version` doesn't work because you get the validation error, whereas `-h|--help` does because validation is skipped. This wasn't a problem in 0.48.0. If you'd like a more concrete example, [this](https://github.com/samuel-lucas6/Cahir/blob/main/src/Cahir/Program.cs) is the program I'm working on. Hope that helps.
