### ISSUE TITLE
Add '-?' as an additional alias for '-h' and '--help', just like 'dotnet -?'

### ISSUE THREAD

**Issue by kzu** [spectreconsole/spectre.console#1547]
It's second nature for me to just type `-?` to get help on stuff. Even in the GitHub CLI, typing `gh -?` (although not an official option to get help) gets you the default help :).

I'd say it's a common enough shorthand for help that it deserves being supported built-in.

**Comment by patriksvensson** [comment]
Sounds like a reasonable thing to add 👍

**Comment by kzu** [comment]
Adding it as another alias/name for the Help command fails with `Encountered invalid character '?' in option name.`

So there are two implementation choices: 
1. Make `?` a valid option name in the parser
2. Convert on the fly from `-?` to `-h` before executing the app

Option 1 would make the alias discoverable, but may have unintended side-effects due to adding a character that's currently not valid.

Option 2 is easier to implement, but makes it a hidden feature.

Thoughts @patriksvensson?

For now, the PR has option 2, for simplicity reasons :)

**Comment by patriksvensson** [comment]
@kzu I have no problem making `-?` a valid option name. I don't think it will have any unforeseen side effects.

**Comment by kzu** [comment]
Fixed!
