### ISSUE TITLE
Support for input forms

### ISSUE THREAD

**Issue by ZenoArrow** [spectreconsole/spectre.console#1618]
**Is your feature request related to a problem? Please describe.**
I'd like to build forms that would allow data to be edited.

**Describe the solution you'd like**
The ability to create forms that allow data to be entered and edited. Ideally it would be good to be able to tab between fields in these forms.

**Describe alternatives you've considered**
Other TUI libraries support this feature, and I've considered using them, but I'd like to be able to do this within Spectre.Console.

**Additional context**
Here's an example of the type of form I'd ideally like to be able to create, it doesn't have to appear in a pop-up dialog as shown in this screenshot, but the general layout and functionality reflects what I'm looking to achieve in Spectre.Console:
https://fosspost.org/wp-content/uploads/2020/06/yapet.png

---
Please upvote :+1: this issue if you are interested in it.

**Comment by patriksvensson** [comment]
Thank you for posting an issue, but this goes beyond the scope of what Spectre.Console is, so this is not something that we will consider. I would recommend you to take a look at something like [Textual](https://textual.textualize.io/) or [GUI.cs](https://github.com/gui-cs/Terminal.Gui)
