### ISSUE TITLE
Question : Is it possible to center a prompt ?

### ISSUE THREAD

**Issue by Mehybinator** [spectreconsole/spectre.console#1619]
Coudn't find any forums to ask my question so here i am, sorry for opening an issue, i was wondering if its possible to center a prompt like a SelectionPrompt<string> in any sort of way ? I looked at Align, Layout, Grid, Panel and they only accept an IRenderable type, but i could not find any way to turn a SelectPrompt to an Renderable type, thanks in advance and i apologize for opening an issue.

**Comment by patriksvensson** [comment]
No this is not possible.

**Comment by Mehybinator** [comment]
Thank you, cheers!
