### ISSUE TITLE
IPrompt: Render prompts in a wrapper

### ISSUE THREAD

**Issue by i-m-luke** [spectreconsole/spectre.console#1670]
I would like to create a TUI based app with a layout similar to Midnight Commander (menu at the top and bottom and a prompt between them). Menus are simple text with commands (e.g., Exit [ESC], etc.). The prompts are async to be able to interrupt them when a menu command key is pressed.

Solutions:
a) Insert the prompt into a table
b) Set TopWrapper and BottomWrapper: wrappers will be rendered in their respective positions

I'm sure if it were easy to implement, it would have been done alread

**Comment by patriksvensson** [comment]
Prompts do not implement `IRenderable`, and are not designed to be used inside tables or similar as stated in our docs. This is by design.
