### ISSUE TITLE
Question: Is it possible to use Spectre.Console to render to string?

### ISSUE THREAD

**Issue by Depact** [spectreconsole/spectre.console#1677]
**Is your feature request related to a problem? Please describe.**
Spectre.Console is amazing, but I'm not found a good way to combine it with ITestOutputHelper, and other ILogger and similar interfaces. I wish to use it with those at least by writing compatibility layer, but I want render to string for it.

**Describe the solution you'd like**
I'd like to be able to render to string. With and without colors, because of all the issues with Ansi colors.

**Describe alternatives you've considered**
Probably there is something like this somewhere in docs or issues, but I wasn't been able to find.

**Additional context**
ITestOutputHelper fundamentally incompatible with live elements. Due to how it connects to CI/CD and not allows to rewrite lines. 

---
Please upvote :+1: this issue if you are interested in it.

**Comment by Depact** [comment]
Found that I can do it like this:
```
    using var writer = new StringWriter();
    var console = AnsiConsole.Create(new AnsiConsoleSettings
    {
      Ansi = AnsiSupport.No,
      ColorSystem = ColorSystemSupport.NoColors,
      Out = new AnsiConsoleOutput(writer)
    });
```
Works for me, I think. Now I want to figure out how to make those settings global in a best way.

**Comment by patriksvensson** [comment]
You can also use the `TestConsole` in the `Spectre.Console.Testing` package that was designed for this.

**Comment by Depact** [comment]
@patriksvensson 'TestConsole' not named like something I should use outside of tests. This gonna cause confusion.

**Comment by patriksvensson** [comment]
Oh, I was under the impression that you wanted to use it for tests.

**Comment by Depact** [comment]
I want to use it for tests too, `TestConsole` definetly sounds great. Thanks for info. I just wanted to use it not only for tests, because this package is really great at making verbose logs

**Comment by patriksvensson** [comment]
Ok, just make sure you take a dependency on `IAnsiConsole` in your code if you want to be able to test it.
