### ISSUE TITLE
Allow Colors to be created from 3-digit hexadecimal codes

### ISSUE THREAD

**Issue by FrankRay78** [spectreconsole/spectre.console#1686]
A [Color](https://github.com/spectreconsole/spectre.console/blob/main/src/Spectre.Console/Color.cs) can be created from a 6-digit hexadecimal code, either by `FromHex` or `TryFromHex` methods.

Support should be added for 3-digit hexadecimal codes.  

eg. `#09C` which is the short version of `#0099CC`

---
Please upvote :+1: this issue if you are interested in it.

**Comment by FrankRay78** [comment]
Great @TheMarteh, I'll be the reviewer/your buddy.  Don't hesitate to ask along the way.

**Comment by TheMarteh** [comment]
Thanks a lot, @FrankRay78 . I've opened up PR https://github.com/spectreconsole/spectre.console/pull/1708 with the implemented changes.
