### ISSUE TITLE
Is it worth exposing `FakeAnsiConsole`?

### ISSUE THREAD

**Issue by mcon** [spectreconsole/spectre.console#238]
**Is your feature request related to a problem? Please describe.**
When testing the rendered output of a console app, the best way seems to be to create a dummy `IAnsiConsole` and wrap that in a `Recorder`, it'd be nice to not have to do the dummy boilerplate.

**Describe the solution you'd like**
It feels like exposing `FakeAnsiConsole` could be useful for testing.

**Describe alternatives you've considered**
It's possible to achieve this with other boilerplate but, as far as I can see, there's not any other good way - all the tests for spectre.console use these fake consoles that aren't exposed.

**Comment by patriksvensson** [comment]
@mcon Would be worth creating a `Spectre.Console.Testing` library that contains something like this. It should however probably be a bit redesigned since it's built for use with Spectre.Console. As an external consumer, there is probably a need for something more flexible.

**Comment by patriksvensson** [comment]
Spectre.Console.Testing has been published to NuGet a while back.
