### ISSUE TITLE
Passing data for Default command

### ISSUE THREAD

**Issue by n-sidorov** [spectreconsole/spectre.console#247]
**Is your feature request related to a problem? Please describe.**
It looks like you can't set `Data` property for "default" command.

**Describe the solution you'd like**
Either use `Data` defined in config for same type of command or ability to specify context for the "default" command, same as regular command.

**Additional context**

Example code:
```csharp
var externalDataObject = new { AdditionalContext = "myContext" };

var app = new CommandApp();
app.SetDefaultCommand<MyCommand>();
app.Configure(config =>
{
    config
        .AddCommand<MyCommand>("myCommand")
        .WithData(externalDataObject);

    config
        .AddCommand<MyAnotherCommand>("myAnotherCommand");
});
```
If you call the app like `myApp myCommand --myArg xxx` then the `MyCommand` will be called and "context" will have `externalDataObject` value, but if you call it like `myapp --myArg xxx`  then the `MyCommand` will be called but "context" will not have `externalDataObject` value.

**Comment by 0xced** [comment]
Note that similarly a _description_ can't be assigned to the default command. My current workaround is to set it through reflection with [ReflectionMagic](https://github.com/ReflectionMagic/ReflectionMagic). 😕

```csharp
using ReflectionMagic;
using Spectre.Console.Cli;

var app = new CommandApp<MyCommand>();
app.Configure(config =>
{
    config.AsDynamic().DefaultCommand.Description = "Description of the default command for the help page";
});
return app.Run(args);
```

**Comment by 0xced** [comment]
I just submitted #1091 to address this issue.

**Comment by Gnbrkm41** [comment]
Ran into a similar issue of not being able to set description for default commands. #1091 would be great if it could be merged!

**Comment by FrankRay78** [comment]
Thank you @0xced, another great PR.

**Comment by 0xced** [comment]
> My current workaround is to set it through reflection.

Replying to myself: I just realized that I can set the description of the default command by simply adding a `[Description]` attribute on `MyCommand` class. 🤦‍♂️
