### ISSUE TITLE
Support alternate screen buffer?

### ISSUE THREAD

**Issue by phil-scott-78** [spectreconsole/spectre.console#250]
**Is your feature request related to a problem? Please describe.**
[Be neat if main and alt buffers were supported](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#alternate-screen-buffer). I want my app to do everything in one buffer then switch back to the main one on exiting and restore the original screen buffer

**Describe the solution you'd like**
Maybe something like 

```csharp
AnsiConsole.Console.SetBuffer(Buffer.Main)
AnsiConsole.Console.SetBuffer(Buffer.Alternate)
```

**Describe alternatives you've considered**
```
AnsiConsole.Console.Write(Segment.Control("\u001b[?1049h")); // alternate
// do stuff
AnsiConsole.Console.Write(Segment.Control("\u001b[?1049l")); // main
```

**Additional context**
This might be cruising for a bruising. Just playing with it by sending in the escape codes by hand screws with things it seems. E.g. tables for some reason get rendered on both on my test app.

**Comment by patriksvensson** [comment]
I'm a little bit hesitant to add support for this tbh, since there isn't a good fallback strategy for terminals that doesn't support ANSI. Adding something like this would change people's assumptions a lot, and once someone runs an app in a terminal lile this, it will fall upon me to "fix it".

Couldn't this be done easily in your app by emitting a Segment with the necessary VT100 sequences for now?

Hope you can see my point of view. I will think about it. Perhaps we could throw if it's not supported?

**Comment by phil-scott-78** [comment]
I hear ya. Makes total sense. 

I'll go ahead and close it.

**Comment by patriksvensson** [comment]
@phil-scott-78 I've been thinking a bit. We could add new capabilities to the Profile so the user can check if it's supported or not, and simply throw an exception if we're on a terminal we know can't handle it.

I'm reopening this issue.

**Comment by Entomy** [comment]
I had prototyped an alternative console API and am looking to deprecate it so I can better focus on other things. How I addressed this problem may be of interest to you.

`Console`, or whatever you're using, exposes a property like `ScreenBuffer` which returns a ref struct which itself is disposable. When this property is accessed, it switches to the alt buffer and returns this ref struct, which when disposed, switches back to the main buffer. This simplifies lifetime management and ensures that the terminal state is restored upon program exit. This property can easily throw if the alt buffer isn't supported.

**Comment by phil-scott-78** [comment]
@Entomy, have you seen PR #308 yet? If not that's even better. I think the implementation you came up with is inline with what @patriksvensson came up with too, but we stalled out right before the finish line looking for confirmation that we were in a good place with the implementation.

If you get a chance could you pull it down and provide any feedback on how it compared with your solution e.g. why ref struct, etc.

Thanks!
