### ISSUE TITLE
Support Type Suggest, Highlight, and Complete Component

### ISSUE THREAD

**Issue by khalidabuhakmeh** [spectreconsole/spectre.console#265]
Given you have a table of results, allow users to "search" through the table by typing. With each character, highlight found results. For example, take a look at the .NET CLI. This table of templates will get big and unmanageable.

![image](https://user-images.githubusercontent.com/228256/108374556-1508cf80-71cf-11eb-97f5-54f1d3d4d58a.png)

Maybe this is a `SearchAndComplete` feature that can wrap other components. It sits and waits for input. As you type, it redraws the nested elements and highlights text.

Highlighted values can be cycled through and used as the input.

![image](https://user-images.githubusercontent.com/228256/108374899-729d1c00-71cf-11eb-8299-f0670bca80c0.png)

Finally, the `SearchAndComplete` feature allows for "templated input".

In this case we `dotnet new {selection}`. Once selected (the user hits enter), the input is replaced with the value.

**Comment by khalidabuhakmeh** [comment]
As an addendum, possibly each element in the `Table` would have a suggested complete value. Thus allowing you to select a "row" but get a consistent autocomplete result.

**Comment by OskarKlintrot** [comment]
This seems related to, but not dup of, #267.
