### ISSUE TITLE
Detect if current terminal supports emojis

### ISSUE THREAD

**Issue by stevenknox** [spectreconsole/spectre.console#266]
Is there currently any way to detect if the current terminal supports Emojis? This would allow optionally using Emojis where supported. Thinking something like:

```csharp 
if (AnsiConsole.Capabilities.Supports.Emoji)
{
    AnsiConsole.MarkupLine(Emoji.Known.CheckBoxWithCheck + " Done");
}
else
{
    AnsiConsole.Markup("Done");
}
```

**Comment by patriksvensson** [comment]
@stevenknox There is no way to detect this to my knowledge. One thing to check for is whether or not the terminal output encoding is Unicode, but it doesn't tell whether or not the terminal supports emojis.

**Comment by stevenknox** [comment]
No worries @patriksvensson - ill try checking for Unicode as suggested 👍

**Comment by pdevito3** [comment]
@stevenknox, might not work everywhere, but I've ran into a similar issue and have, so far, been able to force Unicode encoding with something like `Console.OutputEncoding = Encoding.Unicode;` by just tossing that at the start of my project.

Not sure if there's any downsides or gotchas to this cc @patriksvensson

**Comment by stevenknox** [comment]
Thanks @pdevito3 !
