### ISSUE TITLE
Title for the progress bar

### ISSUE THREAD

**Issue by AntyaDev** [spectreconsole/spectre.console#293]
First, very much thank you for this amazing console! It looks and works really cool!

**Is your feature request related to a problem? Please describe.**
I am working on the load testing tool NBomber and during the test run, I want to display(and dynamically update) some information over the progress bar.

**Describe the solution you'd like**
I want to have the ability to set Title over the progress bar that I can change dynamically.
Here is an example of this functionality: https://github.com/Mpdreamz/shellprogressbar

**Describe alternatives you've considered**
I tried to use columns for this but it doesn't fully solve my issue. One of the problems is rendering the position of the progress bar - it changes based on text length.

**Comment by XGERT420X** [comment]
No prob but the thanks go to the team

**Comment by patriksvensson** [comment]
As @Yaroshvitaliy suggests in #260, it might be a good idea to add support for footers as well.
