### ISSUE TITLE
Progress flickers and breaks when there are too many tasks

### ISSUE THREAD

**Issue by Tyrrrz** [spectreconsole/spectre.console#316]
**Information**
 - OS: Windows
 - Version: 0.38.0
 - Terminal: VS Code, cmd, Terminal (reproducible everywhere)

**Describe the bug**
When using the progress widget, the output starts flickering erratically after some point. My uneducated guess is that the point where it happens is when the tasks stop fitting on the screen. Additionally, scrolling up or down while the progress is ongoing completely breaks the output, causing the output to get duplicated.

Here's a video showcasing what happens (wait till the end to see the whole output without flickering):

https://user-images.githubusercontent.com/1935960/112224493-041b0600-8c34-11eb-9b02-c99561f94fc0.mp4

**To Reproduce**

Here's the code used in above video:

```csharp
using System.Threading;
using System.Linq;
using System.Threading.Tasks;
using System;
using Spectre.Console;

namespace SpectreTest
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var random = new Random();
            using var semaphore = new SemaphoreSlim(5, 5);

            await AnsiConsole.Progress().StartAsync(async ctx =>
            {
                await Task.WhenAll(
                    Enumerable.Range(0, 200).Select(async i =>
                    {
                        await semaphore.WaitAsync();

                        var progress = ctx.AddTask("Task " + i);
                        await Task.Delay(random.Next(100, 3000));
                        progress.Value = progress.MaxValue;

                        semaphore.Release();
                    })
                );
            });
        }
    }
}
```

**Expected behavior**
There should be no flickering and the output should not break if the user scrolls up or down.

**Additional context**
This issue is partially mitigated if I use `HideCompleted(true)` because then the completed tasks don't get displayed and the list is small. However, this also depends on the capacity of semaphore, which is configured in my app by the user.

Even with `HideCompleted(true)` there seem to be issues when the user scrolls up and down. For example, if you write to the console something before you start reporting progress, that text may get overwritten.

If the problem is too difficult to solve, it may also be possible to somehow limit the number of tasks shown on screen, perhaps by having a "...and 57 other" or something similar in the bottom. Ideally, non-completed tasks would show up at the top.

**Comment by patriksvensson** [comment]
@Tyrrrz Yeah, this one is difficult to solve tbh since all tasks will need to be rendered and there is no way for Spectre.Console to know what tasks currently is being visible. I have no idea how this could be solved in a reliable way that works cross terminal.

**Comment by Tyrrrz** [comment]
@patriksvensson 

> @Tyrrrz Yeah, this one is difficult to solve tbh since all tasks will need to be rendered and there is no way for Spectre.Console to know what tasks currently is being visible. I have no idea how this could be solved in a reliable way that works cross terminal.

Maybe something like this could be a possible workaround:

```

Task 1         [--------     ]    70%
Task 2         [--------     ]    70%
Task 3         [------       ]    60%
Task 4         [-----        ]    40%
Task 5         [---          ]    30%
+15 more   [--           ]    10%

```

Show only a specific number of tasks at a time and hide the rest under a group label in the bottom. Show only tasks closest to competition, which haven't completed yet.

**Comment by Tyrrrz** [comment]
> ...since all tasks will need to be rendered

Also, regarding this, would this be still true if the tasks were sorted? For example, if the tasks were sorted by percentage, with higher percentages at the top, Spectre.Console wouldn't need to re-render tasks that have already completed, would it?
