### ISSUE TITLE
Add color aliases

### ISSUE THREAD

**Issue by patriksvensson** [spectreconsole/spectre.console#325]
It would be a good idea to add some aliases for colors that are widely used.

When converting `ConsoleColor.Magenta` and `ConsoleColor.Cyan` to markup code, an exception occurs since the color names don't exist in the xterm-256 color list. There are also some colors with British spelling that might feel awkward to some of our users who are more used to American spelling.

## Aliases

`magenta` should map to `fuchsia`
`cyan` should map to `aqua`
`gray` should map to `grey`
`gray0` should map to `grey0`
`gray37` should map to `grey37`
`gray53` should map to `grey53`
`gray63` should map to `grey63`
`gray69` should map to `grey69`
`gray84` should map to `grey84`
`gray100` should map to `grey100`
`gray3` should map to `grey3`
`gray7` should map to `grey7`
`gray11` should map to `grey11`
`gray15` should map to `grey15`
`gray19` should map to `grey19`
`gray23` should map to `grey23`
`gray27` should map to `grey27`
`gray30` should map to `grey30`
`gray35` should map to `grey35`
`gray39` should map to `grey39`
`gray42` should map to `grey42`
`gray46` should map to `grey46`
`gray50` should map to `grey50`
`gray54` should map to `grey54`
`gray58` should map to `grey58`
`gray62` should map to `grey62`
`gray66` should map to `grey66`
`gray70` should map to `grey70`
`gray74` should map to `grey74`
`gray78` should map to `grey78`
`gray82` should map to `grey82`
`gray85` should map to `grey85`
`gray89` should map to `grey89`
`gray93` should map to `grey93`

**Comment by idormenco** [comment]
Hi, 
Is this issue available ? I would like to work on it.

Thanks

**Comment by patriksvensson** [comment]
@idormenco Absolutely. I would prefer if this was autogenerated somehow though. Take a look at https://github.com/spectreconsole/spectre.console/tree/main/resources/scripts to see how we generate the color tables today.

**Comment by idormenco** [comment]
@patriksvensson I've created a PR with aliases but I do not understand how to reproduce this issue
`When converting ConsoleColor.Magenta and ConsoleColor.Cyan to markup code, an exception occurs since the color names don't exist in the xterm-256 color list.`

Could you provide minimal code to reproduce this issue. 

Thanks a lot
