### ISSUE TITLE
IAnsiConsole.Clear() does not clear the scroll buffer

### ISSUE THREAD

**Issue by wischi-chr** [spectreconsole/spectre.console#337]
**Information**
 - Version: Most recent master: 6121203fee21c2b7f73bb8b1729147e3dce5bdb9

**Describe the bug**
The `IAnsiConsole.Clear()` command does not clear the scroll buffer.

**To Reproduce**
```csharp
using Spectre.Console;
using System;

for (int i = 0; i < 100; i++)
{
    AnsiConsole.WriteLine($"Line {i}");
}

AnsiConsole.Console.Clear(true);
```

**Expected behavior**
I expect the `.Clear()` method to clear everything like `System.Console.Clear()` does.

**Screenshots**
Here is a screenshot after the `Clear()` call, with the example provided above
![image](https://user-images.githubusercontent.com/2495113/113479614-6247b480-9490-11eb-8037-5deb0750da45.png)

**Solution**
I took a look at the source and the wikipedia article for ANSI escape codes and it looks like the clear method isn't implemented correctly.

At the moment is looks like that:
```csharp
// Spectre.Console/Internal/Backends/Ansi/AnsiConsoleBackend.cs
public void Clear(bool home)
{
    Write(new ControlSequence(ED(2)));
    if (home)
    {
        Write(new ControlSequence(CUP(0, 0)));
    }
}
```

According to Wikipedia ED(2) only clears the screen buffer (which the current behaviour does). I also noticed that CUP(0, 0) is wrong because CUP values are 1-based and CUP(1, 1) would be top left.

IMO the method should be changed to
 - ED(3) - _Which would clear the entire buffer like `System.Console.Clear` does_ and
 - CUP(1, 1)

**Comment by wischi-chr** [comment]
I did a few more tests with the cmd terminal and windows terminal and it looks like both are needed to clear everything I'm not sure why ED(3) alone doesn't work because accoring to the wiki article it should.

**Comment by patriksvensson** [comment]
The Bible (https://vt100.net/docs/vt510-rm/ED.html) says it shoud be ED-2.

Are you by any chance using cmd.exe or similar on Windows? They do probably not implement this correctly in that case.

**Comment by patriksvensson** [comment]
CUP 0,0 is also valid: https://vt100.net/docs/vt510-rm/CUP.html

**Comment by wischi-chr** [comment]
**Regarding CUP 0,0**
It looks like that's supported by most terminals, but IMHO it's a completely unintuitive choice.
It probably comes from the fact that most implementations use some variant of `realCoord = MAX(coord, 1)`.

This example also shows why it's probably a very unnatural choice:
```csharp
Console.Write("\u001b[0;0HA");
Console.Write("\u001b[1;3HX");
Console.Write("\u001b[2;2HC");
Console.Write("\u001b[3;3HD");

// This produces a pattern that looks like that:
A X
 C
  D
```
despite having completely different coordinates A and X are on the same line. The special MAX(x,1)` thing results in a situation where the first column and first row have some "unnatural" alias coordinates.

It's a bit like using negative numbers like so: `Console.Write("\u001b[-4;-4HA");`. This also sets the cursor in the top-left position.
So using CUP 0,0 is just as out of range as CUP -4,-4 would be.

**Regarding ED-2**
I've tried it on cmd.exe, windows terminal, Cmder, MobaXterm and all of them behave exactly the same, ED-2 clears the screen but keeps the scroll buffer intact and ED-3 clears the scroll buffer.

The "bible" doesn't show a ED-3 because the VT100 and VT510 don't have a scroll buffer so the behavior would be the same. But all modern terminals have a scroll buffer, that's why ED-3 was introduced to make a distinction between clearing the visible screen/window and clearing the scroll buffer.

ED-3 was introduced for xterm and the behavior has nothing to do with windows.
Here is a unix stackexchange post about the exact same issue tagged with `gnome-terminal`:
https://unix.stackexchange.com/questions/375743/why-clear-do-not-clear-whole-screen

And here is one for OS X
https://apple.stackexchange.com/questions/31872/how-do-i-reset-the-scrollback-in-the-terminal-via-a-shell-command

My previous guess that probably both are needed is also supported in that apple stackexchange answer
> Note that this _[context: ED-3]_ only erases the scroll-back, not the screen. This allows you to erase one or the other, or both by sending two escape sequences.

**Comment by patriksvensson** [comment]
@wischi-chr Awesome summary! You're right; we should change this. 

The big question is whether we always should send `ED2` and `ED3` or if a new capability is needed for this.
It's probably safe to assume that all terminals have some kind of scroll buffer?

**Comment by patriksvensson** [comment]
@wischi-chr Would you be in a position to send a PR for CUP1,1 and clearing the scroll buffer with ED3?

**Comment by wischi-chr** [comment]
> Would you be in a position to send a PR for CUP1,1 and clearing the scroll buffer with ED3?

Yes of course. I will send a PR later this day (am on mobile right now).
