### ISSUE TITLE
ColorSystem mapping wrong (off-by-one error)

### ISSUE THREAD

**Issue by wischi-chr** [spectreconsole/spectre.console#342]
**Information**
Most recent master version 759b16aed9ec5ea86163def34ec0adeb4a4e0cf4

**Describe the bug**
Creating a console with a given ColorSystem always creates the wrong console (unless autodetect is used)

**To Reproduce**
```csharp
var f = new AnsiConsoleFactory();

var console = f.Create(new()
{
    ColorSystem = ColorSystemSupport.EightBit, // set to 8 bit
});

console.WriteLine(console.Profile.ColorSystem.ToString()); // Prints: "TrueColor"
```

**Expected behavior**
Uses the color system that was requested.

**Additional context**
I already took a look at it and it has to with cast that happens on the `ColorSystemSupport` and `ColorSystem` enums because their values don't match (they are offset by 1)

```csharp
public enum ColorSystemSupport
{
    Detect = 0,
    NoColors = 1,
    Legacy = 2,
    Standard = 3,
    EightBit = 4,
    TrueColor = 5,
}

public enum ColorSystem
{
    NoColors = 0,
    Legacy = 1,
    Standard = 2,
    EightBit = 3,
    TrueColor = 4,
}
```

I found the following places where such faulty casts / mappings happen:

| Code                                         | File                                                 | Line |
| -------------------------------------------- | ---------------------------------------------------- | ---- |
| ColorSystem = (ColorSystemSupport)system,    | src/Spectre.Console.Testing/Fakes/FakeAnsiConsole.cs | 35   |
| : (ColorSystem)settings.ColorSystem;         | src/Spectre.Console/AnsiConsoleFactory.cs            | 37   |
| return (int)colorSystem <= (int)ColorSystem; | src/Spectre.Console/Profile.cs                       | 152  |

Here are a few options that came to mind:
1. Shift the values for the `ColorSystem` type by one. This might cause other issues because enums are value types and the default value of the enum would still be zero, an invalid state.
2. Set `Detect` to -1. This has the downside that `Detect` would no longer be the default value for the support type.
3. Don't cast directly via int but implement propper mapping methods
4. Drop the support types and make them nullable and represent the `Detect` state with `null`.

I can send a PR for that fix if you want once it's decided how to resolve it.

**Comment by patriksvensson** [comment]
@wischi-chr I was testing different approaches out and since I already wrote the code I thought I might as well submit the changes I was happy with as a  PR.

I must say that your bug reports are OUTSTANDING!
