### ISSUE TITLE
A way to to use System.Console.WindowWidth for redirected TextWriters.

### ISSUE THREAD

**Issue by wischi-chr** [spectreconsole/spectre.console#359]
**Is your feature request related to a problem? Please describe.**
In the current implementation if one uses a custom TextWriter/Output Stream the `Tty` property returns true and this automatically leads to a situation where `GetHeight()` and `GetWidth()` return some default constants that can't be controlled.

A user of the library can't even prevent that because Profile and Capabilities are both sealed.

I currently use a custom TextWriter that later down the line ultimately writes to the real console out TextWriter, but the way Tty is implemented breaks the width and height detection an causes the output to wrap after 80 characters.

**Describe the solution you'd like**
I'm pretty open to ideas. The end result should be a situation where I can use a custom TextWriter and can somehow hook GetWidth and GetHeight. Manually setting width and height is not a good option because for a real console (like in my case) there are no good options to get a resize event so I would have to constantly poll `System.Console.WindowWidth` and set the width for the profile.

Things I would try/consider:

- A way to overwrite the Tty flag (introduce a setter with a nullable backing field, like width and height in `Profile`)
_Probably the simplest solution?_
- Unseal `Capabilities` so users can change the tty behaviour
- Unseal `Profile` so it can be derived from
- Introduce an `IProfile` interface so `IAnsiConsole` implementations can provide a different profile implementation

**Describe alternatives you've considered**
Polling `System.Console.WindowWidth` and set the width for the profile (nothing I would _seriously_ consider) or somehow fix it in a custom fork. Another possibility is to set `Profile.Width = int.MaxValue;`  and let the terminal do the line breaks, but this of course breaks almost all widgets.

**Comment by patriksvensson** [comment]
@wischi-chr Your case seems to be an edge case, but perhaps (like you said) we could add a setter to the Tty capability if this would unblock you?

**Comment by patriksvensson** [comment]
Another solution we could implement is having some kind of interface that your TextWriter could implement to provide things like Width and Height which we could check. This would give us more flexibility to control things like this.

We could even use this internally for stdout/stderr textwriters by adding an adapter for them.

```csharp
public interface IAnsiConsoleOutput
{
  TextWriter Output { get; }
  bool Tty { get; }
  int? Width { get; }
  int? Height { get; }
}
```

This way we could remove a lot of the hardcoded checks and move that into an adapter of some sort.
```

**Comment by wischi-chr** [comment]
I'm not really blocked in that sense, because I'm currently using a forked version and made Tty settable. I think for the library itself the second solution with the `IAnsiConsoleOutput` interface would be nicer, but it's not time sensitive at all (at least not for me).

**Comment by Frassle** [comment]
Related to this, I'd like a way to tell Spectre to not do it's own wrapping at `Width` and just let the underlying console handle the wrapping. A hacky way of doing that would be to be able to set `Width` to like `Int32.MaxValue`, but slightly nicer would be if I could set `Width` to null and then have things like right justification be like "well justify right makes no sense with null width so either error or just don't justify"

**Comment by patriksvensson** [comment]
@Frassle I can't see that we will change this since it affects a lot of underlying things and how we support renderable layout and similar. Is there a specific reason for wanting this? Could you elaborate a bit more on the use case?

**Comment by Frassle** [comment]
To help match against some current logging behavior. The current code just writes out to console and lets the console do the wrapping which with a decent console means it will reflow word wrap as the terminal is resized. If we switch to writing out with spectre then we get hard breaks at whatever the console width is when we run. 

I think it would also help with writing to things that really don't really have a width like files. If you writing to a file your probably happy for your tables to just width expand to however much they need, but right justification doesn't really make sense. Passing null instead of some large number would let the layout engines do something sensible there.

It would end up pretty much the same as [soft_wrap in rich](https://github.com/willmcgugan/rich/blob/e34eadb3a9354c2469fa2112400ce2690f2663ba/docs/source/console.rst#soft-wrapping).

**Comment by patriksvensson** [comment]
@Frassle Yes, that would work for `Paragraph` i.e. `Write/WriteLine/Markup/MarkupLine`, but not for other kinds of widgets. For example, a table/grid/progress, etc would always need to pad with line breaks.
