### ISSUE TITLE
Capabilities.Tty is confusingly named

### ISSUE THREAD

**Issue by Frassle** [spectreconsole/spectre.console#369]
`Capabilities.Tty` is documented as "Gets a value indicating whether or not console output has been redirected."

This sounds like the opposite of what a `bool Tty` property would mean. Where I'd expect true to mean "this console is a TTY handle" or possibly "this console is a TTY or PTY handle". 

I'd suggest either renaming the property to `IsRedirected` or flipping the current logic around it so it's true when the console is a terminal, it might still benefit from a rename to something like `IsTerminal` and documented as "Gets a value indicating whether or not the console is a TTY or PTY interface"

**Comment by patriksvensson** [comment]
You're correct. Will change this to `IsTerminal` instead.
