### ISSUE TITLE
Environment Variable Handling

### ISSUE THREAD

**Issue by phantlantis** [spectreconsole/spectre.console#405]
**Is your feature request related to a problem? Please describe.**
Common rules of precedence dictates that cli params usually override environment variables, but when I attempt to add some options into the Constructor Initialization piece:
```csharp
public class CreateTicketSettings : CommandSettings
{
    public CreateTicketSettings(string platform)
    {
        var platformEV = System.Environment.GetEnvironmentVariable("PLATFORM");
        if (platform != null)
        {
            Platform = platform;
         }
        else Platform = platformEV;
    }
   
   [Description("Platform to create request for (web, ios, android)")]
   [CommandArgument(0, "<platform>")]
   public string Platform { get; set; }
}
```
I can only ever successfully resolve the type (avoiding "Error: Could not resolve type") if I set it to a required argument only with the angle brackets, but this fails validation because I didn't set the parameter in the CLI.

**Describe the solution you'd like**
Ideally, a more "spectre-native" approach to handling environment variables along with parameters - being able to incorporate them and bind them to specific arguments and options and continue to respect the "required" and "optional" settings within spectre. 

**Describe alternatives you've considered**
@patriksvensson  proposed a good solution for using the Validate() method as a workaround [here.](https://github.com/spectreconsole/spectre.console/discussions/402#discussioncomment-708426)

**Additional context**

**Comment by phil-scott-78** [comment]
@phantlantis, PR #407 is merged in. If you take a look at the example from @patriksvensson it uses an Environmental Variable provider. 

Give that a shot if you get a chance.

**Comment by phantlantis** [comment]
@phil-scott-78 , using 0.39.1-preview.0.19 in my project using that sealed class and EnvironmentVariable attribute worked great! Thanks for your help on this!
