### ISSUE TITLE
Alias for Branches

### ISSUE THREAD

**Issue by chrisdanna** [spectreconsole/spectre.console#411]
Would it be possible to add command like configurations, e.g. Alias and Description for branches? I am having an issue where my branch names are becoming fairly long, and would improve ease of use of my CLI if descriptions and aliases for branches were avaialable.

```c#
app.Configure(config =>
{
  config.AddBranch<AddSettings>("add", add =>
  {
    add.Alias("a") // <-- or something similar
    add.SetDescription("Add something");
    add.AddCommand<AddPackageCommand>("package");
    add.AddCommand<AddReferenceCommand>("reference");
  })
});
```

**Comment by patriksvensson** [comment]
@chrisdanna That sounds like a reasonable thing to add, and I can't see any problems with it. What do you think @phil-scott-78?

**Comment by bddckr** [comment]
Personally I've run into the need once, too. The issue for me was the fact that users might expect or prefer a different name, e.g. `add`/`set` instead of `insert` for branches that "add" multiple different things with a "subcommand" inside the branch.

That being said I wonder if it should be `AddAlias` and allow _multiple_ aliases. I'm curious how to display the alias(es) in the help text 🤔

**Comment by phil-scott-78** [comment]
I see nothing wrong with adding it. It'd be a nice addition 👍

**Comment by idormenco** [comment]
Hello,
Can I try to fix this ?

**Comment by patriksvensson** [comment]
@idormenco That would be great! 👍

**Comment by OskarKlintrot** [comment]
How's it going @idormenco? 😄

**Comment by AlexSuprunQuali** [comment]
Any news?

**Comment by idormenco** [comment]
Hi @AlexSuprunQuali ,
sorry I did not worked on this issue.
Please unassign me

**Comment by ilyahryapko** [comment]
Added PR addressing this issue, check #1131

**Comment by FrankRay78** [comment]
All, thanks to @ilyahryapko you can now add an alias to a branch.  This functionality has now been merged into main.
