### ISSUE TITLE
Support custom characters at the end of a TextPrompt

### ISSUE THREAD

**Issue by mgnslndh** [spectreconsole/spectre.console#413]
**Is your feature request related to a problem? Please describe.**
When I use the `TextPrompt` for a REPL scenario and I want to use the dollar sign `$` as the last character I get a colon `:` added automatically at the end of the prompt. This seems to happen when the prompt is missing a `?` or `:` as the last character.

**Describe the solution you'd like**
I would like to disable the default behavior of automatically adding a character at the end of the prompt.

**Describe alternatives you've considered**
Perhaps the default last character should be configurable so that you can use a property to set it to another value than `:`.

**Comment by patriksvensson** [comment]
Sorry for not responding until now.
A perfectly reasonable thing to expect!
