### ISSUE TITLE
Support cancellation on prompts

### ISSUE THREAD

**Issue by kzu** [spectreconsole/spectre.console#417]
Since it's now trivial to create async Main methods that pass around a `CancellationToken` to cleanly stop a running console app (i.e. `System.CommandLine` makes this very straightforward), it would be useful to cancel prompts by simply cancelling the token (which in `System.CommandLine` is done automatically when hitting `Ctrl+C` so the program has chance to cancel 
ongoing work cleanly).

## Proposed solution

An improvement of the existing `Prompt` methods would receive a new optional parameter and if the token is cancelled, it would immediately return the default value, instead of waiting for a selection. This allows aborting the selection by pressing `Ctrl+C`, for example.

```csharp
public static T Prompt<T>(IPrompt<T> prompt, CancellationToken cancellation = default)
public static T Ask<T>(string prompt, CancellationToken cancellation = default)
public static bool Confirm(string prompt, bool defaultValue = true, CancellationToken cancellation = default)
```

## Alternatives

The return value could be made nullable, so the caller could determine if an actual selection was made or if the prompt was cancelled instead.

```csharp
public static T? Prompt<T>(IPrompt<T> prompt, CancellationToken cancellation = default)
public static T? Ask<T>(string prompt, CancellationToken cancellation = default)
public static bool? Confirm(string prompt, bool defaultValue = true, CancellationToken cancellation = default)
```

Since the caller would presumably still use the passed `cancellation` token to check on pending cancellation requests, it seems an unnecessary breaking change that doesn't add much value, perhaps.

I'd like to gather feedback on whether this is deemed useful and then I can work on a PR as needed.

Thanks

**Comment by patriksvensson** [comment]
@kzu Sounds like a good idea, but I would like to hold off on this until the work with getting async input is complete. I'll update this issue once it is! 👍

**Comment by kzu** [comment]
Awesome, yeah, I noticed that it would be tricky without some async baked-in in the lower layers :)

**Comment by gitfool** [comment]
I would also love to have cancellation support for long running cli commands.

**Comment by kamtschatka** [comment]
I just came across the same requirement as I would like to switch to progress from a prompt if an external event happens, without having to exit the prompt first.
