### ISSUE TITLE
Bugs possibly related to command branches

### ISSUE THREAD

**Issue by jdvor** [spectreconsole/spectre.console#428]
I think I've found at least 2 bugs possibly related to command branches. Here's [repo](https://github.com/jdvor/spectbug) with the example. It's using Spectre.Console 0.39.0.

- Command options from parent (branch) settings are not taken into account / parsed. In this example _PrintBaseSettings.Message_. Result is failing ValidateExamles() and when _-m MESSAGE_ is passed as command line argument the value is ignored. Reproduce by uncommenting the line [Program.cs:L17](https://github.com/jdvor/spectbug/blob/master/Program.cs#L17)
- Dependency injection through type _TypeRegistrar & TypeResolver_ is called for both command type and their settings, not just command constructor dependencies (_IFooService_ for _DecoratedPrintCmd_ in this example). Maybe this is not a bug, but it is at least unexpected and unusual. Reproduce: comment lines [Program.cs:L46-47](https://github.com/jdvor/spectbug/blob/master/Program.cs#L45) and [Program.cs:L50-51](https://github.com/jdvor/spectbug/blob/master/Program.cs#L50).

**Comment by willyt150** [comment]
Thank you very much for your example as a workaround for the Dependency Injection trying to use the TypeRegistrar and TypeResolver for the command's settings!

If this is working as intended, could we get the documentation to include the need to add the command setting to the DI provider?

**Comment by FrankRay78** [comment]
Hello @jdvor, spectre.console just shipped version 0.48 - do you know if the above is still an issue in this version?

**Comment by pisethdanh** [comment]
Hello @FrankRay78, CommandArgument seems to work as per this [documentation](https://spectreconsole.net/cli/composing).

However, CommandOption doesn't seem to be parsed correctly. I am seeing the same issue as OP.

**Comment by patriksvensson** [comment]
This bug has been fixed and will appear in 0.49.
