### ISSUE TITLE
'AnsiConsole' Does not contain a definition for 'Live'

### ISSUE THREAD

**Issue by UltraStudioLTD** [spectreconsole/spectre.console#438]
**Information**
 - OS: Windows 10
 - Code Editor: Visual Studio 2019 Community
 - Terminal: Windows Terminal

**Describe the bug**
'AnsiConsole' Does not contain a definition for 'Live'

**To Reproduce**
```cs
AnsiConsole.Live( /* Something */)
                .Start(ctx =>
                {
                    ctx.Refresh();
                    Thread.Sleep(1000);
                });
```

**Expected behavior**
I expected for it to run without problem since I copy-pasted code from docs, and only removed unnecessary parts but it didn't. Even when I looked into **AnsiConsole** metadata, there wasn't any **Live**. Even **Progress** and **Status** was here, only **Live** wasn't.

**Additional context**
Installed **Spectre.Console** using **NuGet Package Manager** extension inside **Visual Studio**

**Comment by Rafiuth** [comment]
Have you tried using the latest preview version?

**Comment by phil-scott-78** [comment]
@Rafiuth is almost certainly right, Live is still only in the pre-release versions right now. Make sure you are running the latest pre-release.

**Comment by UltraStudioLTD** [comment]
@phil-scott-78 I usually only install **Stable** versions since most bugs are fixed in them and they are *stable*. When I installed **pre-release** version it fixed it.
