### ISSUE TITLE
Live Display (VB.NET)

### ISSUE THREAD

**Issue by haykparanyan** [spectreconsole/spectre.console#440]
**Information**
 - OS: Windows 10 x64
 - Version: 0.39.1 preview 031
 - Terminal: Windows Terminal

**Describe the bug**
System.InvalidCastException: 'Unable to cast object of type 'System.String' to type 'Spectre.Console.Rendering.IRenderable'.'

**Language**
VB.NET

 AnsiConsole.Live(table).Start(Sub(ctx As LiveDisplayContext)
                                          ' Columns
                                          Update(230, Sub() table.AddColumn("Release date"))
                                          ' Rows
                                          Update(70, Function() table.AddRow("May 25, 1977", "[yellow]Star Wars[/] [grey]Ep.[/] [u]IV[/]", "$11,000,000", "$1,554,475", "$775,398,007"))
                                          Update(230, Sub() table.Columns(2).Footer = "$1,633,000,000")
                                 End Sub)

**Comment by phil-scott-78** [comment]
Been a long time since my VB days, but I suspect the issue is setting footer to a string. That property expects an `IRenderable`.  The C# to VB.NET conversion of the footer assignment from the demo would call the extension method which does have an overload for taking a string directly.

```vb
Update(ctx,230, Sub() table.Columns(2).Footer("$1,633,000,000"))
```

I would suggest enabling `OPTION STRICT` for your app when working with Spectre (and any time, really) to avoid runtime issues like this and so you'll get it as a compiler error instead..

**Comment by haykparanyan** [comment]
So what's this? Why I'm getting errors?
![Capture](https://user-images.githubusercontent.com/65831709/120869775-43f15880-c5a8-11eb-86e0-e37f2fca01b4.PNG)

**Comment by phil-scott-78** [comment]
without a project to reproduce the error, I'll have to guess. And my guess you don't have one of the new preview build with the Live component included. Try version `0.39.1-preview.0.31`

**Comment by haykparanyan** [comment]
Here is the project
[ConsoleApp1.zip](https://github.com/spectreconsole/spectre.console/files/6610625/ConsoleApp1.zip)

**Comment by phil-scott-78** [comment]
This is just absolutely littered with basic VB syntax errors. From my testing I'm not seeing any reason there would be an issue with Spectre so unless there is a better reproduction I'm not going to be able to help achy further

**Comment by haykparanyan** [comment]
ok. thanks
