### ISSUE TITLE
Alternative to the obsolete 'Select' function for selecting default items in SelectionPrompt

### ISSUE THREAD

**Issue by stevenknox** [spectreconsole/spectre.console#447]
Is default selection of SelectionPrompt items supported? It looks like a feature was added in this PR https://github.com/spectreconsole/spectre.console/pull/236

However Select is now flagged as obsolete. Is there an alternative ?

**Comment by patriksvensson** [comment]
@stevenknox Good point. I removed it for now since it didn't make sense anymore (items can't be retrieved by indexed). We should really add something that brings back this functionality. Sorry for the inconvenience!

**Comment by patriksvensson** [comment]
@stevenknox Added a PR that solves this for you and should be available in the next version. When fixing this, I realized that you can select items when you add them.

```charp
prompt.AddChoice("Foo").Select();
```
```

**Comment by stevenknox** [comment]
Fantastic @patriksvensson ! Very much appreciated, the tool im building has a lot of defaults so really helps improve the UX
