### ISSUE TITLE
0.40.0 has breaking changes in parameter validation

### ISSUE THREAD

**Issue by devlead** [spectreconsole/spectre.console#448]
There's a bit more that's changed than specified under
* Correct documentation comment text
https://github.com/spectreconsole/spectre.console/releases/tag/0.40.0

0.40.0 broke ABI with ParameterValidationAttribute which should be documented to 

```diff
- public abstract ValidationResult Validate(ICommandParameterInfo parameterInfo, object? value)
+ public abstract ValidationResult Validate(CommandParameterContext context);
```

This means people are blocked to upgrade to 0.40.0 until all their dependencies are updated to 0.40.0. i.e. like if you like us have common validation rules in it's own assembly - it will need to be updated first.

**Comment by patriksvensson** [comment]
@devlead Sorry about this. We're working on better process for releases.
