### ISSUE TITLE
Default values for Ask()

### ISSUE THREAD

**Issue by hugoqribeiro** [spectreconsole/spectre.console#460]
`Ask()` could accept a default value that would be returned when the user simply presses enter, no?

This helps a lot in scenarios where you want, for example, to prompt for something and assume a default value or even set the last input as the default for latter executions of the same prompt...

```
string defaultVatNumber;
(...)
string vatNumber = AnsiConsole.Ask<string>("Enter the VAT number:", defaultVatNumber);
defaultVatNumber = vatNumber;
(...)
```

**Comment by patriksvensson** [comment]
@hugoqribeiro Sounds like a reasonable thing to add! Do you want to submit a PR for this?

**Comment by hugoqribeiro** [comment]
@patriksvensson well... I'm new to spectre.console. I'm not familiar with the API design. May be that's not a great idea. :)

**Comment by nils-a** [comment]
Sounds easy enough - I'll give it a try if that's ok with everyone.

**Comment by patriksvensson** [comment]
@nils-a Absolutely!
