### ISSUE TITLE
Relieve requirements for exclusivity mode when not running against a real console (i.e. in tests)

### ISSUE THREAD

**Issue by Tyrrrz** [spectreconsole/spectre.console#494]
**Is your feature request related to a problem? Please describe.**

When using dynamic displays, Spectre.Console ensures exclusivity through a call to this method:

https://github.com/spectreconsole/spectre.console/blob/5f97f2300cf848e84e90e963ee491042054ae477/src/Spectre.Console/Internal/DefaultExclusivityMode.cs#L37-L55

This makes perfect sense for when the application is running with a real console window. However, when running the application in tests (with an in-memory buffer provided to `AnsiConsoleSettings.Out`), this does not make much sense and forces the user to disable parallelization to avoid an exception.

**Describe the solution you'd like**

If given `(AnsiConsoleOutput.Writer.IsStandardOutput() || AnsiConsoleOutput.Writer.IsStandardError()) == false`, don't impose the single instance limitation on live displays.

**Note** that the current `IsStandardOutput/Error()` checks are a bit flaky. For example, in my case I have a custom `StreamWriter` implementation that wraps the output stream obtained via `Console.OpenStandardOutput()`. Because my instance of `StreamWriter` doesn't match `Console.Out`, it will incorrectly return false. This can be improved by checking the inner stream (via `StreamWriter.BaseStream`) and matching it against [`System.IO.ConsoleStream`](https://source.dot.net/#System.Console/System/IO/ConsoleStream.cs,c0e0ba628fa4c224) (which is unfortunately internal, so some reflection will be required).

Additionally, it seems that Spectre.Console already has a no-op implementation of `IExclusivityMode`, but it is internal: https://github.com/spectreconsole/spectre.console/blob/5f97f2300cf848e84e90e963ee491042054ae477/src/Spectre.Console.Testing/Internal/NoopExclusivityMode.cs#L6-L17

Making it public (and part of the core package) would already help but it would be nice if Spectre could also detect the most appropriate exclusivity mode automatically based on `AnsiConsoleOutput`, as explained earlier.

**Describe alternatives you've considered**

Currently I just programmatically provide a custom implementation of `IExclusivityMode` when running in tests, as that's the simplest workaround:

https://github.com/Tyrrrz/DiscordChatExporter/blob/28de1053f6151a889b497036d603c36f131cf31e/DiscordChatExporter.Cli/Utils/Extensions/ConsoleExtensions.cs#L19-L23

**Additional context**

Failures when parallelization is enabled:

![image](https://user-images.githubusercontent.com/1935960/126204651-114758ea-a844-4aa4-b22f-11a464fd20ed.png)

No failures without parallelization:

![image](https://user-images.githubusercontent.com/1935960/126204781-df81c9d3-583f-48ae-8c22-5132d698a8f0.png)

**Comment by patriksvensson** [comment]
@Tyrrrz Sounds like a perfectly reasonable request to me.
I would prefer this to be something you opt-in to explicitly though, and not using any kind of heuristics.

**Comment by Tyrrrz** [comment]
> I would prefer this to be something you opt-in to explicitly though, and not using any kind of heuristics.

I suppose that can be achieved by making the `NoopExclusivityMode` public and part of the core package (instead of `Spectre.Console.Testing`). Would do you think?

**Comment by patriksvensson** [comment]
I've been thinking about this a bit, and I think it's better that we make the semaphore non-static instead. The exclusivity mode should only be used per console, and now it's shared among all consoles, which frankly makes no sense.

Making the semaphore non-static would solve your issue as well.
