### ISSUE TITLE
MultiSelectionPrompt.AddChoice() in AnsiConsole.Prompt() causes compilation error

### ISSUE THREAD

**Issue by danielmayost** [spectreconsole/spectre.console#499]
**Information**
 - OS: Windows 10
 - Version: 0.41.0

**Describe the bug**
In class `MultiSelectionPrompt` the method `AddChoice` return `IMultiSelectionItem<>` instead `MultiSelectionPrompt<>` which causes compilation error in the following example.

Maybe this is supposed to be the case, and should only use `MultiSelectionPrompt.AddChoices()`, anyway, this is an official example from the documentation.

**To Reproduce**
```
var fruits = AnsiConsole.Prompt(
            new MultiSelectionPrompt<string>()
                .Title("What are your [green]favorite fruits[/]?")
                .NotRequired() // Not required to have a favorite fruit
                .PageSize(10)
                .MoreChoicesText("[grey](Move up and down to reveal more fruits)[/]")
                .InstructionsText(
                    "[grey](Press [blue]<space>[/] to toggle a fruit, " + 
                    "[green]<enter>[/] to accept)[/]")
                .AddChoice("Apple")
                .AddChoices(new[] {
                    "Apricot", "Avocado", 
                    "Banana", "Blackcurrant", "Blueberry",
                    "Cherry", "Cloudberry", "Cocunut",
                }));
```

This code snippet is taken from the example on the website at: 
https://spectreconsole.net/prompts/multiselection

**Comment by patriksvensson** [comment]
The reason `AddChoice` returns `IMultiSelectionItem<>` is so the item can be further configured.
The documentation however should be updated. Thanks for reporting this.
