### ISSUE TITLE
Return group in SelectionPrompt and MultiSelectionPrompt

### ISSUE THREAD

**Issue by Cheesebaron** [spectreconsole/spectre.console#502]
**Is your feature request related to a problem? Please describe.**
I would love when using `SelectionPrompt` or `MultiSelectionPrompt` with choice groups, that I could get both the selected item, but also the group it belongs to as output.

Consider this code:

```csharp
var api = AnsiConsole.Prompt(
    new SelectionPrompt<string>()
        .Title("What API do you want to explore?")
        .PageSize(10)
        .MoreChoicesText("[grey](Move up and down to reveal more options)[/]")
        .AddChoiceGroup("Cloud API", new string []
        {
            "Booking API"
        })
        .AddChoiceGroup("Site API", new string[]
        {
            "Booking API"
        }));
```

If I have the same choice in different groups, I would like to know which group it belongs to.

Right now I would have to wrap the strings in my own little class such as:

```csharp
public class Choice
{
    public string Name { get; set; }
    public string Group { get; set; }

    public override string ToString() => Name;
}
```

**Describe the solution you'd like**

Would be great if somehow `SelectionPrompt` and `MultiSelectionPrompt` could somehow also return the choice group when returning a value.

**Comment by patriksvensson** [comment]
@Cheesebaron I totally get what you're after, but the problem is that `AddChoiceGroup` is just a convenience method to add a single level to the tree. It's also possible to build a selection tree with an arbitrary number of levels.

The result would need to look something like the code below, which I think would make things more complicated than it should be.

```csharp
public class SelectedChoice<T>
{
    public T Value { get; }
    public bool Selected { get; }
    public Choice<T>? Parent { get; }
}
```

Perhaps we could add a method to the tree itself to get the parent of a choice?

```csharp
var group = api.GetParent("Booking API")
```

**Comment by Cheesebaron** [comment]
That could probably work and solve the problem. I guess that would work with any type you use for your groups?

How would that work internally? Some recursive traversing of the groups and matching whether the reference is the same?

**Comment by patriksvensson** [comment]
@Cheesebaron Sorry for not getting back to you about this sooner.
I think most of the stuff for this should be wired up already, so it shouldn't be a super big change.

Is this something that you would consider contributing?

**Comment by Cheesebaron** [comment]
Sure, I could have a look. Need to familiarize myself with the code, but shouldn't be an issue 😄

**Comment by Cheesebaron** [comment]
Go ahead, have been busy with other things. So please do take a stab at it.
