### ISSUE TITLE
Opens the option to expand objects - by removing "sealed"

### ISSUE THREAD

**Issue by danielmayost** [spectreconsole/spectre.console#504]
**Is your feature request related to a problem? Please describe.**
I would be happy if there was more flexibility to expand existing objects in the project, like `ProgressTask`, for that matter, I owe a version of it with a few more Properties.

This was a problem for me with a few other objects like `Table` etc. 

**Describe the solution you'd like**
Why must all objects be locked for expansion, with `sealed`? It will be more flexible to leave users more options.

**Comment by patriksvensson** [comment]
@danielmayost That kind of flexibility leads to a lot of bugs, therefore everything is sealed by default. We prefer to extend things using composition if we can in the first place and avoid inheritance.
