### ISSUE TITLE
Bug: Link Rendering

### ISSUE THREAD

**Issue by stuart-blackler-cko** [spectreconsole/spectre.console#526]
**Information**
 - OS: Windows
 - Version: 0.41.0
 - Terminal: Powershell / Cmd

**Describe the bug**
Links do not render when then `[link=]` format is used. Links render correctly when just using `new Markup("https://google.com")` on some terminals

**To Reproduce**

```c#
if (AnsiConsole.Profile.Capabilities.Links)
{
    AnsiConsole.MarkupLine("[link=https://patriksvensson.se]Click to visit my blog[/]!"); // Does not render as link
    AnsiConsole.MarkupLine("https://patriksvensson.se"); // renders as link
}
else
{
    AnsiConsole.MarkupLine("[red]It looks like your terminal doesn't support links[/]");
    AnsiConsole.MarkupLine("[yellow](╯°□°)╯[/]︵ [blue]┻━┻[/]");
}
```

**Expected behavior**
The link should be rendered

**Screenshots**
Output for the above code:

_Powershell_
![image](https://user-images.githubusercontent.com/51921338/131352354-f4b9e2ba-862a-45f6-8fa5-8daff71a1c45.png)

_Cmd_
![image](https://user-images.githubusercontent.com/51921338/131352850-86852aea-937a-4a3f-b64b-3fd7b90697ef.png)

**Additional context**

Full repo: https://github.com/Im5tu/spectre-console-bug/tree/main/Bug

When testing on `cmd.exe` no links are rendered at all (see above cmd screenshot)

**Comment by patriksvensson** [comment]
@stuart-blackler-cko Thanks for reporting this. Alas, this is not a bug, but the specific VT/ANSI code is not supported by your terminal. We're using some heuristics to determine if this is supported (the `AnsiConsole.Profile.Capabilities.Links`), but this doesn't always work.

**Comment by Im5tu** [comment]
Thanks for the quick response. Completely understand the heuristics, but shouldn't `Click to visit my blog` render as a link if `https://patriksvensson.se` renders as a link?  Or does it fall under the same heuristics?

**Comment by patriksvensson** [comment]
@Im5tu I assume the above screenshot (Powershell) is taken from Windows Terminal?
Windows Terminal renders URL:s automatically. That functionality was added in one version, and the VT/ANSI support was added later.

What version of Windows Terminal are you using?

**Comment by Im5tu** [comment]
It was from the JetBrains interface, so going to broadly assume they are doing the same as the Windows Terminal. Thanks for the explanations and all the work on this lib :)
