### ISSUE TITLE
Borders between Cells?

### ISSUE THREAD

**Issue by omaus** [spectreconsole/spectre.console#529]
**Is your feature request related to a problem? Please describe.**
I'm using Spectre.Console for displaying MS Excel sheets as SpectreTables. I'm happy with it but I miss the possibility to add borders between cells to easily distinguish several rows. Is there an option I missed?

**Describe the solution you'd like**
An option or a table border style that adds borders between cells.

**Describe alternatives you've considered**
Adding a rows that just consist of '─'. Very ugly, but a workaround.

**Comment by patriksvensson** [comment]
@omaus Thanks for raising this issue. However, I think this is a duplicate of #517.
Closing this in favor of the existing one, but thanks for reporting it! Much appreciated!

**Comment by henriksen** [comment]
Fixed in #1304?

**Comment by patriksvensson** [comment]
@henriksen Correct, thanks.
