### ISSUE TITLE
Progress control not updating the Spinner

### ISSUE THREAD

**Issue by OnlyOnePro** [spectreconsole/spectre.console#534]
**Information**
 - OS: Windows 10 19043.1165
 - Version: 0.41.0
 - Terminal: cmd, Terminal

**Describe the bug**
Creating a async Progress Control with a SpinnerColumn as shown on the documentation (https://spectreconsole.net/live/progress) when editing the shown Spinner on the column the spinner doesn't uses the specified style.

**To Reproduce**

```cs await AnsiConsole.Progress()
                    .AutoRefresh(false) // Turn off auto refresh
                    .AutoClear(false)   // Do not remove the task list when done
                    .HideCompleted(false)   // Hide tasks as they are completed
                    .Columns(new ProgressColumn[]
                    {
                        new TaskDescriptionColumn(),    // Task description
                        new ProgressBarColumn(){
                            RemainingStyle = new Style(Color.Black,Color.Black,Decoration.SlowBlink),
                            FinishedStyle = new Style(Color.Green,Color.Green,Decoration.SlowBlink),
                            CompletedStyle= new Style(Color.Green,Color.Green,Decoration.SlowBlink),
                            },        // Progress bar
                        new PercentageColumn(),         // Percentage
                        new RemainingTimeColumn(),      // Remaining time
                        new SpinnerColumn(Spinner.Known.Grenade),            // Spinner
                    }).StartAsync(async ctx => // DO SOME WORK HERE AND UPDATE THE UI);
```

**Expected behavior**
The Progress control shows the Grenade Spinner.

**Screenshots**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/27441273/132855815-57e6eb22-19eb-441e-acec-8967b70bf9ca.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/27441273/132855824-507a7489-f69b-4e69-951f-787cd811526b.png)

**Comment by patriksvensson** [comment]
@OnlyOnePro Thanks for reporting this, but this is not a bug. If the console output encoding isn't Unicode, it will fall back to the default ASCII spinner.

If you're running PowerShell, you can explicitly set the output encoding by running `[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding` before your application, or set the output encoding explicitly with `Console.OutputEncoding = Encoding.UTF8Encoding` in your application.
*Please note that there is no guarantee that the terminal is capable of rendering this correctly if it doesn't support Unicode.*

You can check the output encoding in your console by running `dotnet example info`.

**Comment by patriksvensson** [comment]
@OnlyOnePro I went ahead and closed this, but feel free to re-open if you think I closed this in error, or if you can't get it to work in a terminal with output encoding set to Unicode.
