### ISSUE TITLE
Automatic usage docs for enum options

### ISSUE THREAD

**Issue by koliyo** [spectreconsole/spectre.console#536]
**Is your feature request related to a problem? Please describe.**
I am unable to provide help for enum option values.

Preferably I would like this to be automatic, which is this feature request.

But even without this I am unable to manually supply the help text due to compiletime string requirements of attributes.

**Describe the solution you'd like**
When using an enum option, I would like the command line documentation to list the valid options.

**Describe alternatives you've considered**

I am trying to provide this manually as a workaround. But can not get this to work. This is my config:

```cs

  public enum LogLevel {
    Verbose,
    Debug,
    Info,
    Warning,
    Error
  }


  public class GlobalSettings : CommandSettings {
    public static string LogLevelHelp =>
      string.Join("|", Enum.GetValues<LogLevel>());

    [CommandOption($"-l|--log <{LogLevelHelp}>")]
    public LogLevel Log { get; set; }
  }

```

Which gives the following error

```
Feature 'constant interpolated strings' is not available in C# 9.0. Please use language version 10.0 or greater. [Releaseit]csharp(CS8773)
```

So would it be possible to provide this dynamically, eg using an `Action<string>` as an alternative to static `string` for the 
`CommandOption` constructor?

**Comment by nils-a** [comment]
To answer the question, you added the feature request: No, arguments to attributes must be constant. In c# 10 "constant interpolated strings" were added, but I think all parts of that interpolated string still need to be constant.

You could, however, subclass the `Description` (as Description is probably what you'd want to use anyway) as a work around for the currently non-existent *auto-recognition-and-help-text-generation-for-valid-values-of-options*

If you add an attribute

```cs
[AttributeUsage(AttributeTargets.All)]
public class LogLevelDescriptionAttribute : DescriptionAttribute
{
    public override string Description => "Sets the log level. Valid avalues are: " + string.Join(", ", Enum.GetNames(typeof(LogLevel)));
}
```

And then define your `Log` property like this:

```cs
[CommandOption("-l|--log <LEVEL>")]
[LogLevelDescription]
public LogLevel Log { get; set; }
```

you'll get an output like:

```text
    -l, --log <LEVEL>    Sets the log level. Valid avalues are: Verbose, Debug, Info, Warning, Error
```

**Comment by patriksvensson** [comment]
The comment @nils-a made summarizes things very well, so I'm going to go ahead and close this issue.
