### ISSUE TITLE
Add EnvironmentVariableAttribute example to provided API

### ISSUE THREAD

**Issue by koliyo** [spectreconsole/spectre.console#539]
**Is your feature request related to a problem? Please describe.**
I want to use environment variables to populate options.

**Describe the solution you'd like**
This seems to have already been solved in #407 

But instead of copy pasting the `EnvironmentVariableAttribute` it would be nice if it was part of the `Spectre.Console` API

**Comment by koliyo** [comment]
I have a WIP pull request here, but not yet any tests.

https://github.com/spectreconsole/spectre.console/pull/540

Not sure when I will have time to complete the PR, so please use it as a suggested implementation and make a complete implementation if this looks like a good idea...

**Comment by patriksvensson** [comment]
@koliyo It looks like a good idea, but closing the PR until you have time to revisit it.

**Comment by FrankRay78** [comment]
Not enough desire amonst contributors to implement this feature.

@anyone - feel free (at any time) to reopen, explain the need, and submit a complete PR for it.
