### ISSUE TITLE
`link` to file URIs with spaces throws error

### ISSUE THREAD

**Issue by martinnormark** [spectreconsole/spectre.console#543]
**Information**
 - OS: Windows
 - Version: 11 - 21H2
 - Terminal: Windows Terminal

**Describe the bug**
When rendering `link` in markup, if URI contains spaces it throws an error indicating a style not found.

**To Reproduce**
Render the following:

```csharp
string uri = Markup.Escape(@"C:\temp\asdasdas\test image.jpg");

AnsiConsole.Markup($@"[link={uri}]TEST LINK[/] :link:");
```

**Expected behavior**
Link is rendered and will open image at given location on click.

**Screenshots**
![image](https://user-images.githubusercontent.com/67565/134419623-309a40f4-86c6-4ff0-8c2f-06fdbe009a11.png)

**Additional context**
None

**Comment by patriksvensson** [comment]
@martinnormark Try URL encoding the link. It will also need to be in the format `file:///C:/temp/asdasdas/test%20%image.jpg` for it to work.

**Comment by martinnormark** [comment]
@patriksvensson Thanks, that worked. I tried URL encoding earlier, but missed the `/` instead of `\`.

Thanks 🙌
