### ISSUE TITLE
Is it possible to retrospectively update a table cell? 

### ISSUE THREAD

**Issue by RedEyedDog** [spectreconsole/spectre.console#544]
Hi

I'm trying to make a table like below: 
![image](https://user-images.githubusercontent.com/6059035/134469487-80d560a7-2955-4c42-b2d8-4fdc761b3723.png)

Where each row represents a battle ( the last row being current battle).

I need to be able to go back and update the winner column? right now i'm having to add an extra row with the rest of the columns empty

Thanks

**Comment by patriksvensson** [comment]
@RedEyedDog Currently not possible, but I guess we could add a setter to the `TableRow` indexer.

https://github.com/spectreconsole/spectre.console/blob/main/src/Spectre.Console/Widgets/Table/TableRow.cs#L30

**Comment by RedEyedDog** [comment]
that would be great.. you make it sound and look easy. I'll expect it by the end of the day haha. Would really Improve the functionality a lot :)

**Comment by patriksvensson** [comment]
@RedEyedDog Haha, I don't have time to do anything about this, but perhaps you want to send a PR? 😄

**Comment by RedEyedDog** [comment]
if you think its as simple as adding a setter.. ill take a look no problem

**Comment by RedEyedDog** [comment]
could you possibly explain what kind of project this is and how to build it and test before I issue a PR. I cant see any developer onboarding instructions :O

**Comment by RedEyedDog** [comment]
Just found Contributing.md lol let me read that first

**Comment by patriksvensson** [comment]
@RedEyedDog There is a solution file in the `src` folder which you can open in Visual Studio.
To run a full build with packaging, restore all tools from a command prompt using `dotnet tool restore` and then `dotnet cake`.
Also take a look at: https://github.com/spectreconsole/spectre.console/blob/main/CONTRIBUTING.md

When I think about it, I think we would need to add a new method here: https://github.com/spectreconsole/spectre.console/blob/main/src/Spectre.Console/Widgets/Table/TableRowCollection.cs such as `Update(int row, int column, IRenderable item)` so we can lock the row collection.

**Comment by RedEyedDog** [comment]
Ok so instead of adding a setter for indexing.. you would prefer an Update method? I can do that sir no problem.

I'll go try and figure it out now ;)

**Comment by patriksvensson** [comment]
@RedEyedDog Awesome. Let me know if you run into any problems and I'll try to help out!

**Comment by RedEyedDog** [comment]
Hey looking at the code.. I think you want me to add update method to the Table class and then use "row" for index into his Rows collection and "column" to index TableRow?

**Comment by patriksvensson** [comment]
@RedEyedDog We would want to lock the TableRowCollection when making the change, so I think we need to add an update method to the TableRowCollection. We could add an extension method to `Table` later on that calls the new `Update` method.

**Comment by RedEyedDog** [comment]
thanks.. i'm thinking somthing like this: 
![image](https://user-images.githubusercontent.com/6059035/134480776-b264d966-e537-486d-a5f8-3565fe487478.png)

**Comment by patriksvensson** [comment]
@RedEyedDog Sounds like a plan. Would be great if you could add tests for this as well.

**Comment by RedEyedDog** [comment]
ok great.. easy peasy lemon squeezy ;). Ill add some unit tests no problem

**Comment by RedEyedDog** [comment]
I'm just trying to test locally. I have built successfully and I go to "spectre.console\src\Spectre.Console\bin\Debug\netstandard2.0" and grab the dll. I then copy,  paste into my projects bin folder... but I'm still not seeing my new method?

 I have also added an extension method for the table like so: 
![image](https://user-images.githubusercontent.com/6059035/134487031-5516fe33-4a5f-44e1-90ed-108fdbaba565.png)
and I cant see it

**Comment by RedEyedDog** [comment]
Sorry realised what I was doing, smelly brain fart :@

**Comment by RedEyedDog** [comment]
Worked a treat 
![image](https://user-images.githubusercontent.com/6059035/134489760-8351a46a-1af8-4905-9855-5245d7211796.png)
:)

**Comment by RedEyedDog** [comment]
I'm thinking this naming might be better? what do you think 

![image](https://user-images.githubusercontent.com/6059035/134490147-4b1d0881-251f-4b64-842b-07b02e1919f3.png)

**Comment by RedEyedDog** [comment]
Hey I have issued a PR but its Failing on documentation and not sure why exactly

**Comment by patriksvensson** [comment]
@RedEyedDog Yeah, that's not your fault. We're currently having some problems with documentation and the net 6.0 rc SDK.
I will review your PR tonight when I have some spare time 👍

**Comment by patriksvensson** [comment]
Closed via #546
