### ISSUE TITLE
Low performance rendering big Tree objects

### ISSUE THREAD

**Issue by SergioLuis** [spectreconsole/spectre.console#551]
**Information**
 - OS: macOS
 - Version: Big Sur 11.5.2
 - Terminal: iTerm

**Describe the bug**
Rendering big trees is noticeable slow in spectre.console - moreover compared with other tools in which the same rendering seems to happen instantaneously.

**To Reproduce**
I'm playing with the library by creating a clone of the `tree` utility. For this, first i traverse the FileSystem, then build the `Tree` object, then render it using `AnsiConsole.Render`. This is the detailed log of how much time each operation took:

```text
23:23:49.537 FsTree - Started walking tree '/Users/sluisp/wkspaces/codice'
23:23:50.281 FsTree - Finished walking tree. Found 10703 directories and 95 files
23:23:50.287 FsTreeCommand - Started rendering the tree with AnsiConsole
23:23:50.290 RenderTree - Started building Spectre.Console.Tree object
23:23:50.369 RenderTree - Finished building Spetre.Console.Tree object
23:24:35.030 FsTreeCommand - Finished rendering tree
```

- Traversing the FS: 744ms
- Building the `Spectre.Console.Tree` object: 79ms
- Calling `AnsiConsole.Render` with that tree: 84661ms

As you can see in the logs, the tree is comprised of 10798 nodes. It's quite big, but for a FileSystem I would consider it quite standard. Each node is only plain text - no text colors, no tables, not anything fancy. A exact `tree` clone regarding what goes to the screen.

**Expected behavior**
The rendering could be faster. I'm sure lot's of things are happening behind the scenes, but... maybe there is room for improvement :)

Or maybe I'm using the library wrong and I need to adjust a buffer or something like that for it to work faster, but I didn't found anything documented.

**Comment by phil-scott-78** [comment]
You have a reproduction I could pull down? I'd like to take a look at it in dottrace and see what we can do to speed it up

**Comment by SergioLuis** [comment]
Sure! In the attached ZIP file you can find the directory structure I tested this with.
[fstree-perf-test.zip](https://github.com/spectreconsole/spectre.console/files/7231859/fstree-perf-test.zip)

And in the following GitHub Gist you can find a single-file .NET 5 application that reproduces the case.
https://gist.github.com/SergioLuis/dd34d98dd72cbc102de01326ad701560

**Comment by phil-scott-78** [comment]
Wonderful. If my little guy gets to bed at a reasonable hour I'll be able to take a look tonight I hope

**Comment by phil-scott-78** [comment]
This has been a lot of fun messing with. Just submitted a PR with a huuuuuuuuuuuuge perf gain thanks to this - #552.
