### ISSUE TITLE
Are you able to have a live Table along with status updates at the same time?

### ISSUE THREAD

**Issue by RedEyedDog** [spectreconsole/spectre.console#553]
**Is your feature request related to a problem? Please describe.**
I would like to have a live table with a live status? So imagine a simple table which your waiting to fill out. 
Id like to have a status on what stage its on and to be able to update the table when data is available.

**Describe the solution you'd like**
Some kind of hybrid Status/Progress/Table interface.. 

**Describe alternatives you've considered**
Placing them inside one another but I get a Lock error 
**Additional context**

**Comment by patriksvensson** [comment]
@RedEyedDog Thanks for reporting this, but this is something that we don't support intentionally.
