### ISSUE TITLE
config.SetExceptionHandler is missing

### ISSUE THREAD

**Issue by woutervanranst** [spectreconsole/spectre.console#627]
**Information**
 - Version: 0.42.0

**Describe the bug**
config.SetExceptionHandler is missing in version 0.42.0, as described at the bottom https://spectreconsole.net/cli/exceptions

**To Reproduce**
Empty console project
Copypaste the example at the bottom
Add reference to Spectre.Console 0.42.0
`'IConfigurator' does not contain a definition for 'SetExceptionHandler' and no accessible extension method 'SetExceptionHandler' accepting a first argument of type 'IConfigurator' could be found (are you missing a using directive or an assembly reference)`

This seems to be in main and in the documentation, but not in the code of 0.42 (see https://github.com/spectreconsole/spectre.console/blob/0.42.0/src/Spectre.Console/Cli/ConfiguratorExtensions.cs)

It is present in the preview version

**Comment by patriksvensson** [comment]
This is a new feature that will be available in version 0.43. You can also use this now by installing a pre-release version. The documentation reflects the latest preview documentation.

**Comment by woutervanranst** [comment]
thanks, 'works as designed' :)

**Comment by patriksvensson** [comment]
@woutervanranst You're welcome. I appreciate you opening an issue because now I realize that we should probably mention in our docs that something only is available in preview (or what version it will appear in). 👍
