### ISSUE TITLE
Inject CommandSettings or retrieve during/after run

### ISSUE THREAD

**Issue by woutervanranst** [spectreconsole/spectre.console#628]
Use case (simplified):
* I'm registering a Azure Blob Container Client with accountname and accountkey which are passed as cli commands
* The `CommandSettings` are not available through dependency injection - hence I cannot have this client injected and must manually instantiate it in `Execute(CommandContext ctx, CommandSettings settings) {}` which defeats the purpose of DI somewhaat

Would there be an easy/elegant way to inject the parsed `CommandSettings`?
I feel something may be possible with an `ICommandInterceptor` and/or `ITypeRegistrar.RegisterLazy` (deferring the resolution until the command is fully parsed)?

Alternatively, is there a way where I could get the parsed `CommandSettings` after `CommandApp.Run(args)`? In that case I would set up a second `ServiceCollection` with the parsed `CommandSettings`, the container client, ... and go from there.

**Comment by nils-a** [comment]
@woutervanranst I'm not sure I get what you're aiming at. Are you trying to use the `CommandSettings`, not as part of the command being run, but rather later? Like after `CommandApp.Run(args)`?
