### ISSUE TITLE
Conversion in the default pair deconstructor is wron

### ISSUE THREAD

**Issue by nils-a** [spectreconsole/spectre.console#630]
This was reported in #618 
> The code using the TypeConverter was written backwards (using ConvertTo instead of ConvertFrom) and would thus throw an exception. For example, when converting an enum:
>
> >System.NotSupportedException: 'EnumConverter' is unable to convert 'System.String' to 'System.DayOfWeek'.

**Comment by nils-a** [comment]
0xced could you add a comment here, so I can assign the issue?

**Comment by 0xced** [comment]
Sure!
