### ISSUE TITLE
Documentation of settings containing arrays is incomplete

### ISSUE THREAD

**Issue by nils-a** [spectreconsole/spectre.console#644]
Currently, the use of `arrays` in settings is only [documented](https://spectreconsole.net/cli/settings) for `CommandArguemts` like 

```
[CommandArgument(0, "[name]")]
public string[] Name { get; set; }
```

But not for `CommandOptions`, as asked in #330, #465.

Additionally, the fact that there can be only one *argument vector*, and it needs to be the last argument of the command, is currently not documented at all.

**Comment by FrankRay78** [comment]
The requirements of a PR to address this issue are two fold, namely:

- Document the use of arrays for `CommandOptions`
- Document the fact that there can be only one argument vector, and it needs to be the last argument of the command

The documentation should be located here: https://spectreconsole.net/cli/settings
