### ISSUE TITLE
readme on installing dotnet-example seems wrong 

### ISSUE THREAD

**Issue by ErikEJ** [spectreconsole/spectre.console#654]

**Comment by patriksvensson** [comment]
@ErikEJ Not sure what is wrong. Could you elaborate on this? Thanks!

**Comment by ErikEJ** [comment]
The guide to install dotnet-example I'd

    dotnet tool restore

**Comment by nils-a** [comment]
@ErikEJ Are you seeing an error when running that command? If so, what is the error?

**Comment by patriksvensson** [comment]
@ErikEJ It doesn't install it as a global tool. It's part of the project's tool manifest (dotnet-tools.json).

**Comment by ErikEJ** [comment]
Learned something new today!
