### ISSUE TITLE
Some unit tests other examples are needed for AsyncCommand.

### ISSUE THREAD

**Issue by dlandi** [spectreconsole/spectre.console#676]
I was chatting with @patriksvensson on Twitter and he suggest I look at AsyncCommand for an example project I posted on youtube. 

I checked it out, but I see no unit tests for AsynCommand or examples. 

I suggest that be rectified.

Cheers!

**Comment by FrankRay78** [comment]
Dear @dlandi, I have now submitted PR https://github.com/spectreconsole/spectre.console/pull/1228 which should address this issue.

Specifically, the async command unit tests are located here: https://github.com/spectreconsole/spectre.console/blob/0f15b96ba0d32cb9cf0b80b7b0758eda1c226e18/test/Spectre.Console.Cli.Tests/Unit/CommandAppTests.Async.cs

If you have time, please review and tell me if they meet your expectations. If not, I'd be interested to hear what is missing or needs to change.   Many thanks
