### ISSUE TITLE
Status does not render correctly when output is wrapped

### ISSUE THREAD

**Issue by kevingosse** [spectreconsole/spectre.console#694]
**Information**
 - OS: Windows
 - Version: 0.43.0, the issue is still there in 0.43.1-preview.0.19
 - Terminal: Tested with Windows Terminal and with the built-in cmd

**Describe the bug**
When a line is wrapped because it's bigger than the console width, the status will overwrite it.

**To Reproduce**

```csharp
        static async Task<int> Main(string[] args)
        {
            AnsiConsole.Status()
                .Start("1234567890123456789", ctx =>
                {
                    Thread.Sleep(1000);

                    AnsiConsole.WriteLine(new string('x', Console.WindowWidth + 10));
                });

            return 0;
```

**Expected behavior**
The status should be displayed below the wrapped line.

**Screenshots**

First execution with `Console.WindowWidth` characters, no problem. Second execution with `Console.WindowWidth + 10` characters, part of the line gets overwritten by the status.
![image](https://user-images.githubusercontent.com/11140081/149761837-5c721546-965c-47d7-8bdc-880cd0b8b6f1.png)

**Additional context**
It looks like a variation of https://github.com/spectreconsole/spectre.console/issues/415

**Comment by patriksvensson** [comment]
@franklupo What do you mean by the official version?

**Comment by franklupo** [comment]
Nuget non in preview

**Comment by patriksvensson** [comment]
@franklupo Sorry, I do not follow...
