### ISSUE TITLE
Spectre.Cli not using the latest version of Spectre.Console

### ISSUE THREAD

**Issue by BlackBearFTW** [spectreconsole/spectre.console#696]
**Describe the bug**
When installing the Spectre.Cli Package, the version of Spectre.Console that is being installed is 0.33, instead of version 0.43

**To Reproduce**
Install Spectre.Cli from nugget

**Comment by patriksvensson** [comment]
Spectre.Cli package has been superseded by the Spectre.Console package and will not be updated.
