### ISSUE TITLE
Getting Started examples fail to render emoji and some spinners on Windows

### ISSUE THREAD

**Issue by sldr** [spectreconsole/spectre.console#713]
**Information**
 - OS: Windows 10 Pro
 - Version: 21H2 19044.1466
 - Terminal: Windows Terminal, cmd.exe, PowerShell 5.1 & PowerShell 7.2.1

**Describe the bug**
Tried to render several emojis and didn't find any that worked. The Clock spinner does not work.

**To Reproduce**
I ran the following code on a Windows Terminal (PowerShell 5.1), cmd.exe console, PowerShell 5.1 console, and PowerShell 7.2.1 console. BTW: Blinking only occurs on Windows Terminal.
```c#
    public static async Task<int> Main(string[] args)
    {
      Task COutTask = Console.Out.WriteLineAsync("Hello World!");
      Spectre.Console.AnsiConsole.MarkupLine("[underline red slowblink]Hello[/] World! :globe_showing_europe_africa:");
      await COutTask;
      AnsiConsole.Progress()
        .AutoRefresh(true)    // Turn on auto refresh
        .AutoClear(false)     // Do not remove the task list when done
        .HideCompleted(false) // Hide tasks as they are completed
        .Columns(new ProgressColumn[]
          {
              new TaskDescriptionColumn(),    // Task description
              new ProgressBarColumn(),        // Progress bar
              new PercentageColumn(),         // Percentage
              new RemainingTimeColumn(),      // Remaining time
              new SpinnerColumn(Spinner.Known.Clock),            // Spinner
          })
        .Start(ctx =>
        {
          // Define tasks
          var task1 = ctx.AddTask("[green]Reticulating splines[/]");
          var task2 = ctx.AddTask("[green]Folding space[/]");
          while (!ctx.IsFinished) {
            task1.Increment(1.5);
            Thread.Sleep(20);
            task2.Increment(0.5);
          }
        });
      return 0;
    }
```

**Expected behavior**
I expected the code to produce emojis and the clock spinner. If this is not supported on Windows please update the documentation.

**Screenshots**
![image](https://user-images.githubusercontent.com/9607160/151870201-af6d17be-89c2-4166-b142-b919e5bb1d55.png)

**Additional context**
None for now.

**Comment by patriksvensson** [comment]
@sldr Unicode functionality is only available in terminals that support that. Terminals on Windows that support Unicode is (for example) Windows Terminal. 

You can check whether or not the current terminal supports Unicode via `AnsiConsole.Profile.Capabilities.Unicode`.

In general, you can never assume that a terminal (especially on Windows) supports things like Unicode and there is nothing Spectre.Console can do about this. We do however try to handle stuff gracefully where we can (such as showing the ASCII-spinner instead of garbage output).
