### ISSUE TITLE
Borders are not showing properly

### ISSUE THREAD

**Issue by R-A-R-E** [spectreconsole/spectre.console#737]
**Information**
 - OS:  Windows
 - Version: 0.43.0
 - Terminal: Windows Terminal

**Describe the bug**
When using any border style such as RoundedBorder it is not displayed properly and just shows as straight boxes.

**To Reproduce**
`            AnsiConsole.Write(
       new Panel(new Text("Right adjusted\nRight").RightAligned())
           .Expand()
           .RoundedBorder()
           .Header("[blue]Right[/]")
           .HeaderAlignment(Justify.Right));`

**Expected behavior**
Show a rounded border around the text

**Screenshots**
[Screenshot](https://i.gyazo.com/e0c74338cb2516664f633eefbcbf78fd.png)

**Comment by patriksvensson** [comment]
If your terminal do not support Unicode, it will fall back to using an ANSI border.
