### ISSUE TITLE
Status does not disappear after a choice prompt

### ISSUE THREAD

**Issue by digitaldias** [spectreconsole/spectre.console#742]
**Describe the bug**
This appears to happen inside an AnsiConsole.Status():

After submitting some data for a configuration, when there is a conflict and I need to ask the user for  what to do, 
when I move to the next step inside, the previous ctx.status() does not clear.
See the included gif below. My offending code is: 

Am I doing this wrong?

``` 
            AnsiConsole.Status().Start("Creating configuration...", ctx =>
            {
                ctx.Status("Gathering data...");

                var currentConfig = LoadConfiguration();
                if (currentConfig.Any(c => c.Name.Equals(configName, StringComparison.CurrentCultureIgnoreCase)))
                {
                    var chosen = AnsiConsole.Prompt(new SelectionPrompt<string>()
                        .PageSize(10)
                        .Title($"Configuration '[yellow]{configName.ToUpper()}[/]' already exists. [yellow]Choose an action[/]")                        
                        .AddChoices("Replace", "Rename", "Abort"));

                    switch(chosen)
                    {
                        case "Replace": break;
                        case "Rename": break;
                        default: return;
                    }                        
                }                

                ctx.Status("Testing MongoDb connection");
                Thread.Sleep(1000);
                if(!MongoConfigurationIsValid(mongoServer, mongoDB, mongoPort))
                {
                    AnsiConsole.Markup("[red]Unable to connect to your mongo database![/]");                    
                }

                ctx.Status("Writing configuration");
                Thread.Sleep(1000);
            });
``` 

**Additional context**
![bug_spectre](https://user-images.githubusercontent.com/929421/154796102-65dc2e7b-6143-439d-91ba-f97a38dc617a.gif)

**Comment by jouniheikniemi** [comment]
The [help page](https://spectreconsole.net/prompts/selection) states that "Using prompts inside status or progress displays, are not supported."

Even with the grammatical error, I do think that is your problem, unfortunately. :-(

**Comment by digitaldias** [comment]
> The [help page](https://spectreconsole.net/prompts/selection) states that "Using prompts inside status or progress displays, are not supported."
> 
> Even with the grammatical error, I do think that is your problem, unfortunately. :-(

Yeah, I eventually learned that, I'll mark this as closed if you haven't already. Thanks for the quick reply!
