### ISSUE TITLE
Virus/Unwanted software warning on Windows 10

### ISSUE THREAD

**Issue by lc9er** [spectreconsole/spectre.console#745]
**Information**
 - OS: Windows 10
 - Version: Windows 20H2 (Build 19042.1526), Spectre.Console (0.43.0), .NET 6.0.100
 - Terminal: Windows Terminal

**Describe the bug**
I attempted to run the Quick Start sample on the Spectre site and received the following warning:

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'C:\Users\<PATH>\spectreTest\bin\Debug\net6.0\spectreTest.dll'. Operation did not complete successfully because the file contains a virus or potentially unwanted software. (0x800700E1)
File name: 'C:\Users\<PATH>\spectreTest\bin\Debug\net6.0\spectreTest.dll'
```
It showed up in the event logs as:

Log Name: Application
Source: .NET RUNTIME
Event ID: 1026
Description:
Application: spectreTest.exe
CoreCLR Version: 6.0.21.52210
.NET Version: 6.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'C:\Users\<PATH>\spectreTest\bin\Debug\net6.0\spectreTest.dll'. Operation did not complete successfully because the file contains a virus or potentially unwanted software. (0x800700E1)
File name: 'C:\Users\<PATH>\spectreTest\bin\Debug\net6.0\spectreTest.dll'

**To Reproduce**
1. dotnet new console
2. dotnet add package Spectre.Console
3. Add something to Program.cs
4. dotnet run

**Expected behavior**
The project builds and runs the Quick Start sample.

**Comment by patriksvensson** [comment]
Yeah, there has been a lot false positives lately for some reason. Are you using Microsoft Defender by any chance?

Could you upload your executable to VirusTotal and share your result?

**Comment by phil-scott-78** [comment]
Can you do us a favor and run two more scenarios?

1. Same `spectreTest` project name without our Spectre.Console installed
2. Different project name from `spectreTest` with Spectre.Console installed

**Comment by lc9er** [comment]
I ran the test and it found nothing malicious. I didn't see an option to
export the results, so I'm attaching a screenshot.

**Comment by lc9er** [comment]
I think you're on the right track:

> Same spectreTest project name without our Spectre.Console installed

This throws the same exception, even without Spectre.Console installed.

> Different project name from spectreTest with Spectre.Console installed

This succeeds. I'm able to build the example in the Quick Start (and
others). It does not throw an exception and world as expected.

Thank you for your help on this. Sorry Defender is being weird with the
project.

**Comment by phil-scott-78** [comment]
No worries, made for an interesting Sunday afternoon of troubleshooting. I'm going to leave this open for now as we might poke MS to see about the false positve.

**Comment by phil-scott-78** [comment]
Noticed Spectre.A was updated in [Defender update version 1.359.809.0](https://www.microsoft.com/en-us/wdsi/definitions/antimalware-definition-release-notes?requestVersion=1.359.809.0). I'm not seeing the error anymore so I'm going to go ahead and close this
