### ISSUE TITLE
Add documentation for `Panel` widget

### ISSUE THREAD

**Issue by patriksvensson** [spectreconsole/spectre.console#755]

**Comment by patrickfreilinger** [comment]
Working on this now

**Comment by patriksvensson** [comment]
Awesome! 👍

**Comment by FrankRay78** [comment]
Hello @patrickfreilinger, just checking in to see how you are going with preparing a PR for this issue?

**Comment by patrickfreilinger** [comment]
@FrankRay78 A PR has been merged for this issue. See here: https://github.com/spectreconsole/spectre.console/pull/1016
