### ISSUE TITLE
The type or namespace name 'TextPath' could not be found

### ISSUE THREAD

**Issue by kgnfth** [spectreconsole/spectre.console#776]
spectre.console version 0.43.0
Im getting this error `The type or namespace name 'TextPath' could not be found`

![image](https://user-images.githubusercontent.com/73314940/160292010-0c7d379b-9255-40f1-9139-c28b032a9ac6.png)

```csharp
using Spectre.Console;

namespace ProxyScraper
{
    static class Program
    {
        static void Main()
        {
             var path = new TextPath("C:/This/Path/Is/Too/Long/To/Fit/In/The/Area.txt");
            AnsiConsole.Write(path);
        }
    }
}
```

**Comment by patriksvensson** [comment]
This feature will not be released until 0.44. You will have to reference the latest preview version for this.

**Comment by phil-scott-78** [comment]
You'll need one of the more recent preview releases to use TextPath.

Any feedback on it would be appreciated before we turn it live in the 0.44 release!

**Comment by kgnfth** [comment]
@patriksvensson @phil-scott-78 Aha okey, I did not know.
