### ISSUE TITLE
Allow Selection Item to be sticky

### ISSUE THREAD

**Issue by BlackBearFTW** [spectreconsole/spectre.console#821]
**Describe the solution you'd like**
It would be neat if you could make a selection item sticky, so when you scroll down the items stays on the screen

**Additional context**
For example, a create button above a list of existing items

**Comment by patriksvensson** [comment]
@BlackBearFTW We appreciate your suggestion, but we intentionally will be keeping the functionality of the prompts simple. For more advanced scenarios, such as the one you're suggesting, I would recommend using a full-fledged TUI library such as Gui.cs.
