### ISSUE TITLE
Default implementation of/how to implement ITypeRegistrar?

### ISSUE THREAD

**Issue by thinker227** [spectreconsole/spectre.console#853]
I'm sorry if this does not fit as an issue but I have been unable to find any other location to ask.

I am developing an app using Spectre.Console.Cli and want to pass in some configuration like an `ILogger` into the app. I haven't been able to find a default implementation for `ITypeRegistrar` so I figured I have to implement it myself. I'm using a plain `Dictionary<Type, object>` for storing the objects, although an issue arises with `void Register(Type service, Type implementation)` where on app startup it tries to register a type (`Spectre.Console.Cli.ExplainCommand`) which does not have a parameterless constructor. How are you supposed to implement `ITypeRegistrar` and specifically `Register` in this case? Is there a default implementation in some external package I'm missing?

**Comment by rena0157** [comment]
There are example implementations available here: https://github.com/spectreconsole/spectre.console/tree/main/examples/Cli/Injection/Infrastructure

In addition there is documentation here: https://spectreconsole.net/cli/commandapp
