### ISSUE TITLE
Value starting with `-` is mistreated as extra option 

### ISSUE THREAD

**Issue by sandreas** [spectreconsole/spectre.console#890]
**Information**
 - OS: Linux, Ubuntu 18.04 LTS
 - Version: 0.44
 - Terminal: xterm-256color, zsh

**Describe the bug**
Providing a valid value starting with `-` throws an exception / error, when using the following syntax:
```
# value `-size` is short form for `size descending`
cli-tester test input.mp3 --order-by "-size"

Error: Option 'order-by' is defined but no value has been provided.

       test input.mp3 --order-by -size
                      ^^^^^^^^^^ No value provided
```

Using the syntax with `=` as value separator works like expected:

```
cli-tester test input.mp3 --order-by="-size"

# works like expected, prints out the unmodified option value for `--order-by`
order-by=<-size>

```

**To Reproduce**

- Compile https://github.com/sandreas/tone/tree/main/cli-tester
- Run the above examples

**Expected behavior**
I would expect that option valid values with leading `-` would be correctly handled when NOT using `=` as separator, otherwise the behaviour is inconsistent in my opinion.

**Comment by FrankRay78** [comment]
This is a value bug imho - see the justification here: https://github.com/spectreconsole/spectre.console/issues/959#issuecomment-1292741847

**Comment by FrankRay78** [comment]
This issue can be closed/marked as complete @patriksvensson, now that PR https://github.com/spectreconsole/spectre.console/pull/1048 has been successfully merged.
