### ISSUE TITLE
Implementations of CommandSettings that override Validate() result in CommandRuntimeException

### ISSUE THREAD

**Issue by jcasale** [spectreconsole/spectre.console#925]
**Information**
 - OS: Windows
 - Version: 10.0.20348.887
 - Terminal: Command Prompt

**Describe the bug**
Implementations of `CommandSettings` that override `Validate()` result in a `CommandRuntimeException` instead of a `CommandParseException`.

**To Reproduce**
Enable `PropagateExceptions` in the `CommandApp`, derive from `CommandSettings`, override `Validate()` and return an error.

**Expected behavior**
As the purpose of `Validate()` is to implement custom syntax validation, I expect when an error is returned, a `CommandParseException` is thrown instead of a `CommandRuntimeException`.

**Additional context**
This makes it impossible to catch a syntax error and handle it using an alternative process.

**Comment by patriksvensson** [comment]
@jcasale Since the problem occurs in runtime due to external factors (input being received via arguments), this is considered a runtime exception and not a parse exception (which means something is wrong with how Spectre.Console.Cli has been configured).
