### ISSUE TITLE
Analyzer nuget package misconfigured

### ISSUE THREAD

**Issue by lonix1** [spectreconsole/spectre.console#932]
The [nuget page](https://www.nuget.org/packages/Spectre.Console.Analyzer) for the analyzer has this:
````xml
<PackageReference Include="Spectre.Console.Analyzer" Version="0.44.0" />
````

But it's an analyzer, so it should be:
````xml
<PackageReference Include="Spectre.Console.Analyzer" Version="0.44.0">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
</PackageReference>
````

For example, [see here](https://www.nuget.org/packages/AsyncFixer#package-reference).

I assume this has something to do with the way the nuget was packaged.

**Comment by patriksvensson** [comment]
Ah, I think we would need to add `<DevelopmentDependency>true</DevelopmentDependency>` to the `Spectre.Console.csproj`.

If you're up for doing this, a PR is very welcome.
