### ISSUE TITLE
Add documentation for markup links

### ISSUE THREAD

**Issue by patriksvensson** [spectreconsole/spectre.console#958]

**Comment by GaryMcD** [comment]
I was just perusing other issues and saw links mentioned, I had no idea this functionality existed.

I would be up for taking a stab at adding this to the docs! Would be good for getting my feet wet in contributing, as I have never done that before... at least not publicly, at work I have done PRs, but its the wild west there. 😝 

**_Requesting permission to take ownership of this item_** @patriksvensson

**Comment by phil-scott-78** [comment]
Jump on it, @GaryMcD. Happy to help with any questions you have on the process too

**Comment by phil-scott-78** [comment]
This was closed with #961
