### ISSUE TITLE
Recent Blog Posts have incorrect post date

### ISSUE THREAD

**Issue by tpill90** [spectreconsole/spectre.console#962]
**Describe the bug**
Every post on the Recent Blog Posts page (https://spectreconsole.net/blog/) has the same exact date, `Sunday, September 11, 2022`.  It looks like this date might be automatically incrementing daily, maybe because CI/CD pushes the latest build daily?

**Expected behavior**
To see the date the blog posts were actually posted 😋

**Screenshots**
![Screenshot 2022-09-11 113824](https://user-images.githubusercontent.com/766513/189536247-ff8ec7f7-4f08-4812-8f4a-6f223413c4f5.png)

**Comment by phil-scott-78** [comment]
Got a bit more explicit with the date formats in the blog posts and things are looking better.

Good catch and thanks for taking the time to report!

![Screenshot_20220911-230349.png](https://user-images.githubusercontent.com/2447331/189566425-d369c4ec-ffc7-4ec1-ae95-1cff7c57cd02.png)
