### ISSUE TITLE
Proposal: automatically display default values of options in the help page

### ISSUE THREAD

**Issue by 0xced** [spectreconsole/spectre.console#973]
**Is your feature request related to a problem? Please describe.**
This is not a problem but a proposal to improve the help page of CLI commands.

**Describe the solution you'd like**
Spectre.Console.Cli supports the `DefaultValueAttribute` to specify a default value for a command option. It would be nice to use this information to automatically display default values in the help page.

**Describe alternatives you've considered**
The current alternative is to repeat the default value in the option description text. This could easily lead to desynchronized _documented_ default value and _actual_ default value. Also, a new column would make the default values stand out.

**Additional context**
Here's what I quickly prototyped. I'll submit a proper pull request if this idea is appealing to you.

Running the Demo example with `run --help` before:
![image](https://user-images.githubusercontent.com/51363/191960644-41ee44d9-16ba-4c44-81ee-f88a7c030907.png)

Running the Demo example with `run --help` after:
![image](https://user-images.githubusercontent.com/51363/191961509-85588914-8606-410d-ad4e-b2b42a401608.png)

**Comment by phil-scott-78** [comment]
I like it, especially if the behavior could be opt-in. I'd be tempted to see what it looks like with default value in-line with with the help text myself e.g. for `-c` the text "The default is `Debug`." is appended rather than needing another column of text.

**Comment by 0xced** [comment]
Here's how it would look like:
<img width="1226" src="https://user-images.githubusercontent.com/51363/192049204-d1262fc2-85ca-4782-b956-409a5b7f69c1.png">

Personally, I prefer the version with the additional _DEFAULT_ column.

I'll have a look at how we could make this behaviour opt-in (or opt-out).

**Comment by 0xced** [comment]
I think I nailed the opt-in part:

```c#
var app = new CommandApp();
app.Configure(config =>
{
    config.WriteOptionsDefaultValues();
});
```
I'm not 100% sure about the `WriteOptionsDefaultValues` method name but the underlying implementation is in place, see https://github.com/0xced/spectre.console/commit/6fe8d2872ff9d8f78feb3b4d86c5195486a37c12

**Comment by FrankRay78** [comment]
Hi @phil-scott-78 - at the moment the PR is coded to show the default values in the help by default (excuse the pun). This strictly speaking doesn't break functional backward compatibility, however may cause problems in the (unlikely?) event consumers are somehow consuming the help output eg. in the same way Spectre uses Verify.  However, they do have the ability to turn off this feature by `config.DisableOptionsDefaultValues();` to revert to existing behaviour. Do you have a view on this?

**Comment by FrankRay78** [comment]
Hi @0xced, firstly what a cracking idea and thank you for implementing it.  I really like it and would be keen to incorporate it into the codebase.  

However, (apologies), I've been doing some edge case testing and with very long default values eg:

```csharp
public class CatSettings : MammalSettings
{
    [CommandOption("--agility <VALUE>")]
    [TypeConverter(typeof(CatAgilityConverter))]
    [DefaultValue(int.MinValue)]
    [Description("The agility between 0 and 100.")]
    [PositiveNumberValidator("Agility cannot be negative.")]
    public int Agility { get; set; }

    // I ADDED THE FOLLOWING ---->
    [CommandOption("--description <VALUE>")]
    [DefaultValue("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id diam at lacus vehicula lacinia pharetra et ante. Fusce ut neque sit amet lacus posuere aliquam et non dui. Vivamus nec leo volutpat mi pretium gravida rutrum sed lacus. In scelerisque turpis erat, non efficitur augue vestibulum ut. Vestibulum euismod urna id euismod pretium. Vestibulum laoreet congue tortor tempus pharetra. Nam in luctus erat. Quisque sollicitudin gravida imperdiet.")]
    [Description("A very long value.")]
    public string Description { get; set; }
}
```

The console wrapping messes up the alignment of the help text for the other commands, see:

![image](https://user-images.githubusercontent.com/52075808/208169268-a17f761f-d29c-4fca-8e68-1f4e3404ca61.png)

BUT it does appear to cope well with fairly long (my judgement here, on behalf of the users) defaults, see: 

![image](https://user-images.githubusercontent.com/52075808/208169761-dd103edd-10f6-4993-9d90-f3a7b35fec4f.png)

Any thoughts?  I guess we could....

1. Do nothing about it - buyer beware
2. Truncate it perhaps eg  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. [500 more characters follow]"
3. Have a option somewhere so the user can toggle the truncate on/off
4. Wrap the full default value IN the default column, AND ALSO, wrap the description IN the description column (if need be) - see image below

![image](https://user-images.githubusercontent.com/52075808/208170456-ca5a4f9e-328f-4b8a-b46c-4b0021ce1d18.png)

Any other ideas?

**Comment by 0xced** [comment]
> 1. Do nothing about it - buyer beware

Why not! (See also my replies to 2. and 6.)

> 2. Have the display of default values turned off by default - the user needs to explicitly turn it on

I think having it on by default is better for discoverability of the feature. It's easier to search how to turn off the feature if you don't like it than learning about a nice feature you have no idea could exist.

> 3. Truncate it perhaps eg "Lorem ipsum dolor sit amet, consectetur adipiscing elit. [500 more characters follow]"

The example you gave here is really pathologically long. In real life scenarios, I don't think people would design CLI options with such long default values. I have tried this feature on a few projects and the longest default value I came up with was a connection string, so something along those lines:

```
Data Source=myServerAddress;Initial Catalog=myDataBase;Integrated Security=SSPI;TrustServerCertificate=true
```

Also, truncating could be bad as it could hide crucial information (like in the connection string example).

> 4. Have an option somewhere so the user can toggle the truncate on/off

I think this is overkill.

> 5. Have an option called something like "HideLongDefaultValuesInHelp", defaulted to true

I also think this is overkill and would make the feature too much convoluted.

> 6. Wrap the full default value IN the default column, AND ALSO, wrap the description IN the description column (if need be) - see image below

It would be really nice as it would solve all the problems related to long default values in a very elegant way. Now, that's where it becomes really interesting as it's actually already working, at least on macOS! I tried to add a very long _Lorem ipsum_ default value in the `Demo` sample project and here's how it renders, with perfectly wrapped columns (builtin Terminal app at the top and iTerm at the bottom).

So the question becomes: why does text in a grid wraps fine on macOS but doesn't properly wrap in the Windows command prompt?

<img width="1792" alt="Wrapped columns in help text" src="https://user-images.githubusercontent.com/51363/208247812-4a8dd97c-acf9-4568-80bc-017ed1e6e43f.png">

Also, I have just rebased the `help-options-default-value` onto `main` and adapted a few things to be compatible with the recently merged #953.

**Comment by phil-scott-78** [comment]
I think this is some good stuff as is. I'm gonna side with @0xced here, I think we could spend a ton of time trying to keep devs from shooting themselves in the foot with outrageous data but with this being something they are hard coding it isn't like something an end user would be breaking.

I feel like this is in good shape. I want to pull it down later tonight after my little guy goes to bed and I'll merge it in after my quick run through.

Long term @patriksvensson and I have discussed making a custom Help Writer something that could be plugged in. That way users wouldn't need a million levers and buttons to toggle to get things to their liking - we could provide output that should meet most use cases but those that want to get into the weeds could use their own implementation.

**Comment by FrankRay78** [comment]
I'm in agreement too @0xced and @phil-scott-78 - the OOTB value here is great and should be turned on by default. The windows terminal wrap edge case can be raised as a separate issue for someone to look into and isn't big enough to hold up the merge. 

My only comment is, given existing expectations have been updated to include the DEFAULT column, should we now add one test to include the output for when the user has opted-out of showing a default? 

Excellent work.

**Comment by 0xced** [comment]
> should we now add one test to include the output for when the user has opted-out of showing a default?

Good point! I have added a test covering this scenario in 47cd07027445e57e6eb53c2b303c973a82c6e826.

**Comment by FrankRay78** [comment]
FYI.  Looks like the text wrapping not respecting the table column also affects Linux: (Ubuntu 22.04, .Net SDK 7.0)

![image](https://user-images.githubusercontent.com/52075808/209394596-b2104933-6bee-4690-93ee-938338fa31ee.png)

(I will raise this as a separate issue to fix, once the code for this issue has been merged)
