### ISSUE TITLE
Support Markdown rendering

### ISSUE THREAD

**Issue by khalidabuhakmeh** [spectreconsole/spectre.console#98]
Allow folks to take a markdown file and render it to the console.

https://github.com/charmbracelet/glow

**Comment by mcon** [comment]
I'm going to have a shot at this, looks like it's not too tricky to use https://github.com/xoofx/markdig

**Comment by mcon** [comment]
PR here if anyone's interested: https://github.com/spectresystems/spectre.console/pull/204
