### ISSUE TITLE
AnsiConsole.Ask<DateTime> format date to dd/mm/YYYY

### ISSUE THREAD

**Issue by samuelguesnier** [spectreconsole/spectre.console#988]
**Is your feature request related to a problem? Please describe.**

`DateTime creationDate = AnsiConsole.Ask<DateTime>("What is the client creation date: ");` The user will type the date in dd/mm/YYYY format, but .NET thinks it's mm/dd/YYYY format.

**Describe the solution you'd like**
Adding a parameter to specify which format to use

**Comment by sowa705** [comment]
I can work on it

**Comment by danielklecha** [comment]
@samuelguesnier @sowa705 PR was merged. Should we close this issue?
